//API enums
const materialAPINames = ["", "ACACIA_BOAT", "ACACIA_BUTTON", "ACACIA_DOOR", "ACACIA_FENCE", "ACACIA_FENCE_GATE", "ACACIA_LEAVES", "ACACIA_LOG", "ACACIA_PLANKS", "ACACIA_PRESSURE_PLATE", "ACACIA_SAPLING", "ACACIA_SIGN", "ACACIA_SLAB", "ACACIA_STAIRS", "ACACIA_TRAPDOOR", "ACACIA_WALL_SIGN", "ACACIA_WOOD", "ACTIVATOR_RAIL", "AIR", "ALLIUM", "AMETHYST_BLOCK", "AMETHYST_CLUSTER", "AMETHYST_SHARD", "ANCIENT_DEBRIS", "ANDESITE", "ANDESITE_SLAB", "ANDESITE_STAIRS", "ANDESITE_WALL", "ANVIL", "APPLE", "ARMOR_STAND", "ARROW", "ATTACHED_MELON_STEM", "ATTACHED_PUMPKIN_STEM", "AXOLOTL_BUCKET", "AXOLOTL_SPAWN_EGG", "AZALEA", "AZALEA_LEAVES", "AZURE_BLUET", "BAKED_POTATO", "BAMBOO", "BAMBOO_SAPLING", "BARREL", "BARRIER", "BASALT", "BAT_SPAWN_EGG", "BEACON", "BEDROCK", "BEE_NEST", "BEE_SPAWN_EGG", "BEEF", "BEEHIVE", "BEETROOT", "BEETROOT_SEEDS", "BEETROOT_SOUP", "BEETROOTS", "BELL", "BIG_DRIPLEAF", "BIG_DRIPLEAF_STEM", "BIRCH_BOAT", "BIRCH_BUTTON", "BIRCH_DOOR", "BIRCH_FENCE", "BIRCH_FENCE_GATE", "BIRCH_LEAVES", "BIRCH_LOG", "BIRCH_PLANKS", "BIRCH_PRESSURE_PLATE", "BIRCH_SAPLING", "BIRCH_SIGN", "BIRCH_SLAB", "BIRCH_STAIRS", "BIRCH_TRAPDOOR", "BIRCH_WALL_SIGN", "BIRCH_WOOD", "BLACK_BANNER", "BLACK_BED", "BLACK_CANDLE", "BLACK_CANDLE_CAKE", "BLACK_CARPET", "BLACK_CONCRETE", "BLACK_CONCRETE_POWDER", "BLACK_DYE", "BLACK_GLAZED_TERRACOTTA", "BLACK_SHULKER_BOX", "BLACK_STAINED_GLASS", "BLACK_STAINED_GLASS_PANE", "BLACK_TERRACOTTA", "BLACK_WALL_BANNER", "BLACK_WOOL", "BLACKSTONE", "BLACKSTONE_SLAB", "BLACKSTONE_STAIRS", "BLACKSTONE_WALL", "BLAST_FURNACE", "BLAZE_POWDER", "BLAZE_ROD", "BLAZE_SPAWN_EGG", "BLUE_BANNER", "BLUE_BED", "BLUE_CANDLE", "BLUE_CANDLE_CAKE", "BLUE_CARPET", "BLUE_CONCRETE", "BLUE_CONCRETE_POWDER", "BLUE_DYE", "BLUE_GLAZED_TERRACOTTA", "BLUE_ICE", "BLUE_ORCHID", "BLUE_SHULKER_BOX", "BLUE_STAINED_GLASS", "BLUE_STAINED_GLASS_PANE", "BLUE_TERRACOTTA", "BLUE_WALL_BANNER", "BLUE_WOOL", "BONE", "BONE_BLOCK", "BONE_MEAL", "BOOK", "BOOKSHELF", "BOW", "BOWL", "BRAIN_CORAL", "BRAIN_CORAL_BLOCK", "BRAIN_CORAL_FAN", "BRAIN_CORAL_WALL_FAN", "BREAD", "BREWING_STAND", "BRICK", "BRICK_SLAB", "BRICK_STAIRS", "BRICK_WALL", "BRICKS", "BROWN_BANNER", "BROWN_BED", "BROWN_CANDLE", "BROWN_CANDLE_CAKE", "BROWN_CARPET", "BROWN_CONCRETE", "BROWN_CONCRETE_POWDER", "BROWN_DYE", "BROWN_GLAZED_TERRACOTTA", "BROWN_MUSHROOM", "BROWN_MUSHROOM_BLOCK", "BROWN_SHULKER_BOX", "BROWN_STAINED_GLASS", "BROWN_STAINED_GLASS_PANE", "BROWN_TERRACOTTA", "BROWN_WALL_BANNER", "BROWN_WOOL", "BUBBLE_COLUMN", "BUBBLE_CORAL", "BUBBLE_CORAL_BLOCK", "BUBBLE_CORAL_FAN", "BUBBLE_CORAL_WALL_FAN", "BUCKET", "BUDDING_AMETHYST", "BUNDLE", "CACTUS", "CAKE", "CALCITE", "CAMPFIRE", "CANDLE", "CANDLE_CAKE", "CARROT", "CARROT_ON_A_STICK", "CARROTS", "CARTOGRAPHY_TABLE", "CARVED_PUMPKIN", "CAT_SPAWN_EGG", "CAULDRON", "CAVE_AIR", "CAVE_SPIDER_SPAWN_EGG", "CAVE_VINES", "CAVE_VINES_PLANT", "CHAIN", "CHAIN_COMMAND_BLOCK", "CHAINMAIL_BOOTS", "CHAINMAIL_CHESTPLATE", "CHAINMAIL_HELMET", "CHAINMAIL_LEGGINGS", "CHARCOAL", "CHEST", "CHEST_MINECART", "CHICKEN", "CHICKEN_SPAWN_EGG", "CHIPPED_ANVIL", "CHISELED_DEEPSLATE", "CHISELED_NETHER_BRICKS", "CHISELED_POLISHED_BLACKSTONE", "CHISELED_QUARTZ_BLOCK", "CHISELED_RED_SANDSTONE", "CHISELED_SANDSTONE", "CHISELED_STONE_BRICKS", "CHORUS_FLOWER", "CHORUS_FRUIT", "CHORUS_PLANT", "CLAY", "CLAY_BALL", "CLOCK", "COAL", "COAL_BLOCK", "COAL_ORE", "COARSE_DIRT", "COBBLED_DEEPSLATE", "COBBLED_DEEPSLATE_SLAB", "COBBLED_DEEPSLATE_STAIRS", "COBBLED_DEEPSLATE_WALL", "COBBLESTONE", "COBBLESTONE_SLAB", "COBBLESTONE_STAIRS", "COBBLESTONE_WALL", "COBWEB", "COCOA", "COCOA_BEANS", "COD", "COD_BUCKET", "COD_SPAWN_EGG", "COMMAND_BLOCK", "COMMAND_BLOCK_MINECART", "COMPARATOR", "COMPASS", "COMPOSTER", "CONDUIT", "COOKED_BEEF", "COOKED_CHICKEN", "COOKED_COD", "COOKED_MUTTON", "COOKED_PORKCHOP", "COOKED_RABBIT", "COOKED_SALMON", "COOKIE", "COPPER_BLOCK", "COPPER_INGOT", "COPPER_ORE", "CORNFLOWER", "COW_SPAWN_EGG", "CRACKED_DEEPSLATE_BRICKS", "CRACKED_DEEPSLATE_TILES", "CRACKED_NETHER_BRICKS", "CRACKED_POLISHED_BLACKSTONE_BRICKS", "CRACKED_STONE_BRICKS", "CRAFTING_TABLE", "CREEPER_BANNER_PATTERN", "CREEPER_HEAD", "CREEPER_SPAWN_EGG", "CREEPER_WALL_HEAD", "CRIMSON_BUTTON", "CRIMSON_DOOR", "CRIMSON_FENCE", "CRIMSON_FENCE_GATE", "CRIMSON_FUNGUS", "CRIMSON_HYPHAE", "CRIMSON_NYLIUM", "CRIMSON_PLANKS", "CRIMSON_PRESSURE_PLATE", "CRIMSON_ROOTS", "CRIMSON_SIGN", "CRIMSON_SLAB", "CRIMSON_STAIRS", "CRIMSON_STEM", "CRIMSON_TRAPDOOR", "CRIMSON_WALL_SIGN", "CROSSBOW", "CRYING_OBSIDIAN", "CUT_COPPER", "CUT_COPPER_SLAB", "CUT_COPPER_STAIRS", "CUT_RED_SANDSTONE", "CUT_RED_SANDSTONE_SLAB", "CUT_SANDSTONE", "CUT_SANDSTONE_SLAB", "CYAN_BANNER", "CYAN_BED", "CYAN_CANDLE", "CYAN_CANDLE_CAKE", "CYAN_CARPET", "CYAN_CONCRETE", "CYAN_CONCRETE_POWDER", "CYAN_DYE", "CYAN_GLAZED_TERRACOTTA", "CYAN_SHULKER_BOX", "CYAN_STAINED_GLASS", "CYAN_STAINED_GLASS_PANE", "CYAN_TERRACOTTA", "CYAN_WALL_BANNER", "CYAN_WOOL", "DAMAGED_ANVIL", "DANDELION", "DARK_OAK_BOAT", "DARK_OAK_BUTTON", "DARK_OAK_DOOR", "DARK_OAK_FENCE", "DARK_OAK_FENCE_GATE", "DARK_OAK_LEAVES", "DARK_OAK_LOG", "DARK_OAK_PLANKS", "DARK_OAK_PRESSURE_PLATE", "DARK_OAK_SAPLING", "DARK_OAK_SIGN", "DARK_OAK_SLAB", "DARK_OAK_STAIRS", "DARK_OAK_TRAPDOOR", "DARK_OAK_WALL_SIGN", "DARK_OAK_WOOD", "DARK_PRISMARINE", "DARK_PRISMARINE_SLAB", "DARK_PRISMARINE_STAIRS", "DAYLIGHT_DETECTOR", "DEAD_BRAIN_CORAL", "DEAD_BRAIN_CORAL_BLOCK", "DEAD_BRAIN_CORAL_FAN", "DEAD_BRAIN_CORAL_WALL_FAN", "DEAD_BUBBLE_CORAL", "DEAD_BUBBLE_CORAL_BLOCK", "DEAD_BUBBLE_CORAL_FAN", "DEAD_BUBBLE_CORAL_WALL_FAN", "DEAD_BUSH", "DEAD_FIRE_CORAL", "DEAD_FIRE_CORAL_BLOCK", "DEAD_FIRE_CORAL_FAN", "DEAD_FIRE_CORAL_WALL_FAN", "DEAD_HORN_CORAL", "DEAD_HORN_CORAL_BLOCK", "DEAD_HORN_CORAL_FAN", "DEAD_HORN_CORAL_WALL_FAN", "DEAD_TUBE_CORAL", "DEAD_TUBE_CORAL_BLOCK", "DEAD_TUBE_CORAL_FAN", "DEAD_TUBE_CORAL_WALL_FAN", "DEBUG_STICK", "DEEPSLATE", "DEEPSLATE_BRICK_SLAB", "DEEPSLATE_BRICK_STAIRS", "DEEPSLATE_BRICK_WALL", "DEEPSLATE_BRICKS", "DEEPSLATE_COAL_ORE", "DEEPSLATE_COPPER_ORE", "DEEPSLATE_DIAMOND_ORE", "DEEPSLATE_EMERALD_ORE", "DEEPSLATE_GOLD_ORE", "DEEPSLATE_IRON_ORE", "DEEPSLATE_LAPIS_ORE", "DEEPSLATE_REDSTONE_ORE", "DEEPSLATE_TILE_SLAB", "DEEPSLATE_TILE_STAIRS", "DEEPSLATE_TILE_WALL", "DEEPSLATE_TILES", "DETECTOR_RAIL", "DIAMOND", "DIAMOND_AXE", "DIAMOND_BLOCK", "DIAMOND_BOOTS", "DIAMOND_CHESTPLATE", "DIAMOND_HELMET", "DIAMOND_HOE", "DIAMOND_HORSE_ARMOR", "DIAMOND_LEGGINGS", "DIAMOND_ORE", "DIAMOND_PICKAXE", "DIAMOND_SHOVEL", "DIAMOND_SWORD", "DIORITE", "DIORITE_SLAB", "DIORITE_STAIRS", "DIORITE_WALL", "DIRT", "DIRT_PATH", "DISPENSER", "DOLPHIN_SPAWN_EGG", "DONKEY_SPAWN_EGG", "DRAGON_BREATH", "DRAGON_EGG", "DRAGON_HEAD", "DRAGON_WALL_HEAD", "DRIED_KELP", "DRIED_KELP_BLOCK", "DRIPSTONE_BLOCK", "DROPPER", "DROWNED_SPAWN_EGG", "EGG", "ELDER_GUARDIAN_SPAWN_EGG", "ELYTRA", "EMERALD", "EMERALD_BLOCK", "EMERALD_ORE", "ENCHANTED_BOOK", "ENCHANTED_GOLDEN_APPLE", "ENCHANTING_TABLE", "END_CRYSTAL", "END_GATEWAY", "END_PORTAL", "END_PORTAL_FRAME", "END_ROD", "END_STONE", "END_STONE_BRICK_SLAB", "END_STONE_BRICK_STAIRS", "END_STONE_BRICK_WALL", "END_STONE_BRICKS", "ENDER_CHEST", "ENDER_EYE", "ENDER_PEARL", "ENDERMAN_SPAWN_EGG", "ENDERMITE_SPAWN_EGG", "EVOKER_SPAWN_EGG", "EXPERIENCE_BOTTLE", "EXPOSED_COPPER", "EXPOSED_CUT_COPPER", "EXPOSED_CUT_COPPER_SLAB", "EXPOSED_CUT_COPPER_STAIRS", "FARMLAND", "FEATHER", "FERMENTED_SPIDER_EYE", "FERN", "FILLED_MAP", "FIRE", "FIRE_CHARGE", "FIRE_CORAL", "FIRE_CORAL_BLOCK", "FIRE_CORAL_FAN", "FIRE_CORAL_WALL_FAN", "FIREWORK_ROCKET", "FIREWORK_STAR", "FISHING_ROD", "FLETCHING_TABLE", "FLINT", "FLINT_AND_STEEL", "FLOWER_BANNER_PATTERN", "FLOWER_POT", "FLOWERING_AZALEA", "FLOWERING_AZALEA_LEAVES", "FOX_SPAWN_EGG", "FROSTED_ICE", "FURNACE", "FURNACE_MINECART", "GHAST_SPAWN_EGG", "GHAST_TEAR", "GILDED_BLACKSTONE", "GLASS", "GLASS_BOTTLE", "GLASS_PANE", "GLISTERING_MELON_SLICE", "GLOBE_BANNER_PATTERN", "GLOW_BERRIES", "GLOW_INK_SAC", "GLOW_ITEM_FRAME", "GLOW_LICHEN", "GLOW_SQUID_SPAWN_EGG", "GLOWSTONE", "GLOWSTONE_DUST", "GOAT_SPAWN_EGG", "GOLD_BLOCK", "GOLD_INGOT", "GOLD_NUGGET", "GOLD_ORE", "GOLDEN_APPLE", "GOLDEN_AXE", "GOLDEN_BOOTS", "GOLDEN_CARROT", "GOLDEN_CHESTPLATE", "GOLDEN_HELMET", "GOLDEN_HOE", "GOLDEN_HORSE_ARMOR", "GOLDEN_LEGGINGS", "GOLDEN_PICKAXE", "GOLDEN_SHOVEL", "GOLDEN_SWORD", "GRANITE", "GRANITE_SLAB", "GRANITE_STAIRS", "GRANITE_WALL", "GRASS", "GRASS_BLOCK", "GRAVEL", "GRAY_BANNER", "GRAY_BED", "GRAY_CANDLE", "GRAY_CANDLE_CAKE", "GRAY_CARPET", "GRAY_CONCRETE", "GRAY_CONCRETE_POWDER", "GRAY_DYE", "GRAY_GLAZED_TERRACOTTA", "GRAY_SHULKER_BOX", "GRAY_STAINED_GLASS", "GRAY_STAINED_GLASS_PANE", "GRAY_TERRACOTTA", "GRAY_WALL_BANNER", "GRAY_WOOL", "GREEN_BANNER", "GREEN_BED", "GREEN_CANDLE", "GREEN_CANDLE_CAKE", "GREEN_CARPET", "GREEN_CONCRETE", "GREEN_CONCRETE_POWDER", "GREEN_DYE", "GREEN_GLAZED_TERRACOTTA", "GREEN_SHULKER_BOX", "GREEN_STAINED_GLASS", "GREEN_STAINED_GLASS_PANE", "GREEN_TERRACOTTA", "GREEN_WALL_BANNER", "GREEN_WOOL", "GRINDSTONE", "GUARDIAN_SPAWN_EGG", "GUNPOWDER", "HANGING_ROOTS", "HAY_BLOCK", "HEART_OF_THE_SEA", "HEAVY_WEIGHTED_PRESSURE_PLATE", "HOGLIN_SPAWN_EGG", "HONEY_BLOCK", "HONEY_BOTTLE", "HONEYCOMB", "HONEYCOMB_BLOCK", "HOPPER", "HOPPER_MINECART", "HORN_CORAL", "HORN_CORAL_BLOCK", "HORN_CORAL_FAN", "HORN_CORAL_WALL_FAN", "HORSE_SPAWN_EGG", "HUSK_SPAWN_EGG", "ICE", "INFESTED_CHISELED_STONE_BRICKS", "INFESTED_COBBLESTONE", "INFESTED_CRACKED_STONE_BRICKS", "INFESTED_DEEPSLATE", "INFESTED_MOSSY_STONE_BRICKS", "INFESTED_STONE", "INFESTED_STONE_BRICKS", "INK_SAC", "IRON_AXE", "IRON_BARS", "IRON_BLOCK", "IRON_BOOTS", "IRON_CHESTPLATE", "IRON_DOOR", "IRON_HELMET", "IRON_HOE", "IRON_HORSE_ARMOR", "IRON_INGOT", "IRON_LEGGINGS", "IRON_NUGGET", "IRON_ORE", "IRON_PICKAXE", "IRON_SHOVEL", "IRON_SWORD", "IRON_TRAPDOOR", "ITEM_FRAME", "JACK_O_LANTERN", "JIGSAW", "JUKEBOX", "JUNGLE_BOAT", "JUNGLE_BUTTON", "JUNGLE_DOOR", "JUNGLE_FENCE", "JUNGLE_FENCE_GATE", "JUNGLE_LEAVES", "JUNGLE_LOG", "JUNGLE_PLANKS", "JUNGLE_PRESSURE_PLATE", "JUNGLE_SAPLING", "JUNGLE_SIGN", "JUNGLE_SLAB", "JUNGLE_STAIRS", "JUNGLE_TRAPDOOR", "JUNGLE_WALL_SIGN", "JUNGLE_WOOD", "KELP", "KELP_PLANT", "KNOWLEDGE_BOOK", "LADDER", "LANTERN", "LAPIS_BLOCK", "LAPIS_LAZULI", "LAPIS_ORE", "LARGE_AMETHYST_BUD", "LARGE_FERN", "LAVA", "LAVA_BUCKET", "LAVA_CAULDRON", "LEAD", "LEATHER", "LEATHER_BOOTS", "LEATHER_CHESTPLATE", "LEATHER_HELMET", "LEATHER_HORSE_ARMOR", "LEATHER_LEGGINGS", "LECTERN", "LEVER", "LIGHT", "LIGHT_BLUE_BANNER", "LIGHT_BLUE_BED", "LIGHT_BLUE_CANDLE", "LIGHT_BLUE_CANDLE_CAKE", "LIGHT_BLUE_CARPET", "LIGHT_BLUE_CONCRETE", "LIGHT_BLUE_CONCRETE_POWDER", "LIGHT_BLUE_DYE", "LIGHT_BLUE_GLAZED_TERRACOTTA", "LIGHT_BLUE_SHULKER_BOX", "LIGHT_BLUE_STAINED_GLASS", "LIGHT_BLUE_STAINED_GLASS_PANE", "LIGHT_BLUE_TERRACOTTA", "LIGHT_BLUE_WALL_BANNER", "LIGHT_BLUE_WOOL", "LIGHT_GRAY_BANNER", "LIGHT_GRAY_BED", "LIGHT_GRAY_CANDLE", "LIGHT_GRAY_CANDLE_CAKE", "LIGHT_GRAY_CARPET", "LIGHT_GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE_POWDER", "LIGHT_GRAY_DYE", "LIGHT_GRAY_GLAZED_TERRACOTTA", "LIGHT_GRAY_SHULKER_BOX", "LIGHT_GRAY_STAINED_GLASS", "LIGHT_GRAY_STAINED_GLASS_PANE", "LIGHT_GRAY_TERRACOTTA", "LIGHT_GRAY_WALL_BANNER", "LIGHT_GRAY_WOOL", "LIGHT_WEIGHTED_PRESSURE_PLATE", "LIGHTNING_ROD", "LILAC", "LILY_OF_THE_VALLEY", "LILY_PAD", "LIME_BANNER", "LIME_BED", "LIME_CANDLE", "LIME_CANDLE_CAKE", "LIME_CARPET", "LIME_CONCRETE", "LIME_CONCRETE_POWDER", "LIME_DYE", "LIME_GLAZED_TERRACOTTA", "LIME_SHULKER_BOX", "LIME_STAINED_GLASS", "LIME_STAINED_GLASS_PANE", "LIME_TERRACOTTA", "LIME_WALL_BANNER", "LIME_WOOL", "LINGERING_POTION", "LLAMA_SPAWN_EGG", "LODESTONE", "LOOM", "MAGENTA_BANNER", "MAGENTA_BED", "MAGENTA_CANDLE", "MAGENTA_CANDLE_CAKE", "MAGENTA_CARPET", "MAGENTA_CONCRETE", "MAGENTA_CONCRETE_POWDER", "MAGENTA_DYE", "MAGENTA_GLAZED_TERRACOTTA", "MAGENTA_SHULKER_BOX", "MAGENTA_STAINED_GLASS", "MAGENTA_STAINED_GLASS_PANE", "MAGENTA_TERRACOTTA", "MAGENTA_WALL_BANNER", "MAGENTA_WOOL", "MAGMA_BLOCK", "MAGMA_CREAM", "MAGMA_CUBE_SPAWN_EGG", "MAP", "MEDIUM_AMETHYST_BUD", "MELON", "MELON_SEEDS", "MELON_SLICE", "MELON_STEM", "MILK_BUCKET", "MINECART", "MOJANG_BANNER_PATTERN", "MOOSHROOM_SPAWN_EGG", "MOSS_BLOCK", "MOSS_CARPET", "MOSSY_COBBLESTONE", "MOSSY_COBBLESTONE_SLAB", "MOSSY_COBBLESTONE_STAIRS", "MOSSY_COBBLESTONE_WALL", "MOSSY_STONE_BRICK_SLAB", "MOSSY_STONE_BRICK_STAIRS", "MOSSY_STONE_BRICK_WALL", "MOSSY_STONE_BRICKS", "MOVING_PISTON", "MULE_SPAWN_EGG", "MUSHROOM_STEM", "MUSHROOM_STEW", "MUSIC_DISC_11", "MUSIC_DISC_13", "MUSIC_DISC_BLOCKS", "MUSIC_DISC_CAT", "MUSIC_DISC_CHIRP", "MUSIC_DISC_FAR", "MUSIC_DISC_MALL", "MUSIC_DISC_MELLOHI", "MUSIC_DISC_OTHERSIDE", "MUSIC_DISC_PIGSTEP", "MUSIC_DISC_STAL", "MUSIC_DISC_STRAD", "MUSIC_DISC_WAIT", "MUSIC_DISC_WARD", "MUTTON", "MYCELIUM", "NAME_TAG", "NAUTILUS_SHELL", "NETHER_BRICK", "NETHER_BRICK_FENCE", "NETHER_BRICK_SLAB", "NETHER_BRICK_STAIRS", "NETHER_BRICK_WALL", "NETHER_BRICKS", "NETHER_GOLD_ORE", "NETHER_PORTAL", "NETHER_QUARTZ_ORE", "NETHER_SPROUTS", "NETHER_STAR", "NETHER_WART", "NETHER_WART_BLOCK", "NETHERITE_AXE", "NETHERITE_BLOCK", "NETHERITE_BOOTS", "NETHERITE_CHESTPLATE", "NETHERITE_HELMET", "NETHERITE_HOE", "NETHERITE_INGOT", "NETHERITE_LEGGINGS", "NETHERITE_PICKAXE", "NETHERITE_SCRAP", "NETHERITE_SHOVEL", "NETHERITE_SWORD", "NETHERRACK", "NOTE_BLOCK", "OAK_BOAT", "OAK_BUTTON", "OAK_DOOR", "OAK_FENCE", "OAK_FENCE_GATE", "OAK_LEAVES", "OAK_LOG", "OAK_PLANKS", "OAK_PRESSURE_PLATE", "OAK_SAPLING", "OAK_SIGN", "OAK_SLAB", "OAK_STAIRS", "OAK_TRAPDOOR", "OAK_WALL_SIGN", "OAK_WOOD", "OBSERVER", "OBSIDIAN", "OCELOT_SPAWN_EGG", "ORANGE_BANNER", "ORANGE_BED", "ORANGE_CANDLE", "ORANGE_CANDLE_CAKE", "ORANGE_CARPET", "ORANGE_CONCRETE", "ORANGE_CONCRETE_POWDER", "ORANGE_DYE", "ORANGE_GLAZED_TERRACOTTA", "ORANGE_SHULKER_BOX", "ORANGE_STAINED_GLASS", "ORANGE_STAINED_GLASS_PANE", "ORANGE_TERRACOTTA", "ORANGE_TULIP", "ORANGE_WALL_BANNER", "ORANGE_WOOL", "OXEYE_DAISY", "OXIDIZED_COPPER", "OXIDIZED_CUT_COPPER", "OXIDIZED_CUT_COPPER_SLAB", "OXIDIZED_CUT_COPPER_STAIRS", "PACKED_ICE", "PAINTING", "PANDA_SPAWN_EGG", "PAPER", "PARROT_SPAWN_EGG", "PEONY", "PETRIFIED_OAK_SLAB", "PHANTOM_MEMBRANE", "PHANTOM_SPAWN_EGG", "PIG_SPAWN_EGG", "PIGLIN_BANNER_PATTERN", "PIGLIN_BRUTE_SPAWN_EGG", "PIGLIN_SPAWN_EGG", "PILLAGER_SPAWN_EGG", "PINK_BANNER", "PINK_BED", "PINK_CANDLE", "PINK_CANDLE_CAKE", "PINK_CARPET", "PINK_CONCRETE", "PINK_CONCRETE_POWDER", "PINK_DYE", "PINK_GLAZED_TERRACOTTA", "PINK_SHULKER_BOX", "PINK_STAINED_GLASS", "PINK_STAINED_GLASS_PANE", "PINK_TERRACOTTA", "PINK_TULIP", "PINK_WALL_BANNER", "PINK_WOOL", "PISTON", "PISTON_HEAD", "PLAYER_HEAD", "PLAYER_WALL_HEAD", "PODZOL", "POINTED_DRIPSTONE", "POISONOUS_POTATO", "POLAR_BEAR_SPAWN_EGG", "POLISHED_ANDESITE", "POLISHED_ANDESITE_SLAB", "POLISHED_ANDESITE_STAIRS", "POLISHED_BASALT", "POLISHED_BLACKSTONE", "POLISHED_BLACKSTONE_BRICK_SLAB", "POLISHED_BLACKSTONE_BRICK_STAIRS", "POLISHED_BLACKSTONE_BRICK_WALL", "POLISHED_BLACKSTONE_BRICKS", "POLISHED_BLACKSTONE_BUTTON", "POLISHED_BLACKSTONE_PRESSURE_PLATE", "POLISHED_BLACKSTONE_SLAB", "POLISHED_BLACKSTONE_STAIRS", "POLISHED_BLACKSTONE_WALL", "POLISHED_DEEPSLATE", "POLISHED_DEEPSLATE_SLAB", "POLISHED_DEEPSLATE_STAIRS", "POLISHED_DEEPSLATE_WALL", "POLISHED_DIORITE", "POLISHED_DIORITE_SLAB", "POLISHED_DIORITE_STAIRS", "POLISHED_GRANITE", "POLISHED_GRANITE_SLAB", "POLISHED_GRANITE_STAIRS", "POPPED_CHORUS_FRUIT", "POPPY", "PORKCHOP", "POTATO", "POTATOES", "POTION", "POTTED_ACACIA_SAPLING", "POTTED_ALLIUM", "POTTED_AZALEA_BUSH", "POTTED_AZURE_BLUET", "POTTED_BAMBOO", "POTTED_BIRCH_SAPLING", "POTTED_BLUE_ORCHID", "POTTED_BROWN_MUSHROOM", "POTTED_CACTUS", "POTTED_CORNFLOWER", "POTTED_CRIMSON_FUNGUS", "POTTED_CRIMSON_ROOTS", "POTTED_DANDELION", "POTTED_DARK_OAK_SAPLING", "POTTED_DEAD_BUSH", "POTTED_FERN", "POTTED_FLOWERING_AZALEA_BUSH", "POTTED_JUNGLE_SAPLING", "POTTED_LILY_OF_THE_VALLEY", "POTTED_OAK_SAPLING", "POTTED_ORANGE_TULIP", "POTTED_OXEYE_DAISY", "POTTED_PINK_TULIP", "POTTED_POPPY", "POTTED_RED_MUSHROOM", "POTTED_RED_TULIP", "POTTED_SPRUCE_SAPLING", "POTTED_WARPED_FUNGUS", "POTTED_WARPED_ROOTS", "POTTED_WHITE_TULIP", "POTTED_WITHER_ROSE", "POWDER_SNOW", "POWDER_SNOW_BUCKET", "POWDER_SNOW_CAULDRON", "POWERED_RAIL", "PRISMARINE", "PRISMARINE_BRICK_SLAB", "PRISMARINE_BRICK_STAIRS", "PRISMARINE_BRICKS", "PRISMARINE_CRYSTALS", "PRISMARINE_SHARD", "PRISMARINE_SLAB", "PRISMARINE_STAIRS", "PRISMARINE_WALL", "PUFFERFISH", "PUFFERFISH_BUCKET", "PUFFERFISH_SPAWN_EGG", "PUMPKIN", "PUMPKIN_PIE", "PUMPKIN_SEEDS", "PUMPKIN_STEM", "PURPLE_BANNER", "PURPLE_BED", "PURPLE_CANDLE", "PURPLE_CANDLE_CAKE", "PURPLE_CARPET", "PURPLE_CONCRETE", "PURPLE_CONCRETE_POWDER", "PURPLE_DYE", "PURPLE_GLAZED_TERRACOTTA", "PURPLE_SHULKER_BOX", "PURPLE_STAINED_GLASS", "PURPLE_STAINED_GLASS_PANE", "PURPLE_TERRACOTTA", "PURPLE_WALL_BANNER", "PURPLE_WOOL", "PURPUR_BLOCK", "PURPUR_PILLAR", "PURPUR_SLAB", "PURPUR_STAIRS", "QUARTZ", "QUARTZ_BLOCK", "QUARTZ_BRICKS", "QUARTZ_PILLAR", "QUARTZ_SLAB", "QUARTZ_STAIRS", "RABBIT", "RABBIT_FOOT", "RABBIT_HIDE", "RABBIT_SPAWN_EGG", "RABBIT_STEW", "RAIL", "RAVAGER_SPAWN_EGG", "RAW_COPPER", "RAW_COPPER_BLOCK", "RAW_GOLD", "RAW_GOLD_BLOCK", "RAW_IRON", "RAW_IRON_BLOCK", "RED_BANNER", "RED_BED", "RED_CANDLE", "RED_CANDLE_CAKE", "RED_CARPET", "RED_CONCRETE", "RED_CONCRETE_POWDER", "RED_DYE", "RED_GLAZED_TERRACOTTA", "RED_MUSHROOM", "RED_MUSHROOM_BLOCK", "RED_NETHER_BRICK_SLAB", "RED_NETHER_BRICK_STAIRS", "RED_NETHER_BRICK_WALL", "RED_NETHER_BRICKS", "RED_SAND", "RED_SANDSTONE", "RED_SANDSTONE_SLAB", "RED_SANDSTONE_STAIRS", "RED_SANDSTONE_WALL", "RED_SHULKER_BOX", "RED_STAINED_GLASS", "RED_STAINED_GLASS_PANE", "RED_TERRACOTTA", "RED_TULIP", "RED_WALL_BANNER", "RED_WOOL", "REDSTONE", "REDSTONE_BLOCK", "REDSTONE_LAMP", "REDSTONE_ORE", "REDSTONE_TORCH", "REDSTONE_WALL_TORCH", "REDSTONE_WIRE", "REPEATER", "REPEATING_COMMAND_BLOCK", "RESPAWN_ANCHOR", "ROOTED_DIRT", "ROSE_BUSH", "ROTTEN_FLESH", "SADDLE", "SALMON", "SALMON_BUCKET", "SALMON_SPAWN_EGG", "SAND", "SANDSTONE", "SANDSTONE_SLAB", "SANDSTONE_STAIRS", "SANDSTONE_WALL", "SCAFFOLDING", "SCULK_SENSOR", "SCUTE", "SEA_LANTERN", "SEA_PICKLE", "SEAGRASS", "SHEARS", "SHEEP_SPAWN_EGG", "SHIELD", "SHROOMLIGHT", "SHULKER_BOX", "SHULKER_SHELL", "SHULKER_SPAWN_EGG", "SILVERFISH_SPAWN_EGG", "SKELETON_HORSE_SPAWN_EGG", "SKELETON_SKULL", "SKELETON_SPAWN_EGG", "SKELETON_WALL_SKULL", "SKULL_BANNER_PATTERN", "SLIME_BALL", "SLIME_BLOCK", "SLIME_SPAWN_EGG", "SMALL_AMETHYST_BUD", "SMALL_DRIPLEAF", "SMITHING_TABLE", "SMOKER", "SMOOTH_BASALT", "SMOOTH_QUARTZ", "SMOOTH_QUARTZ_SLAB", "SMOOTH_QUARTZ_STAIRS", "SMOOTH_RED_SANDSTONE", "SMOOTH_RED_SANDSTONE_SLAB", "SMOOTH_RED_SANDSTONE_STAIRS", "SMOOTH_SANDSTONE", "SMOOTH_SANDSTONE_SLAB", "SMOOTH_SANDSTONE_STAIRS", "SMOOTH_STONE", "SMOOTH_STONE_SLAB", "SNOW", "SNOW_BLOCK", "SNOWBALL", "SOUL_CAMPFIRE", "SOUL_FIRE", "SOUL_LANTERN", "SOUL_SAND", "SOUL_SOIL", "SOUL_TORCH", "SOUL_WALL_TORCH", "SPAWNER", "SPECTRAL_ARROW", "SPIDER_EYE", "SPIDER_SPAWN_EGG", "SPLASH_POTION", "SPONGE", "SPORE_BLOSSOM", "SPRUCE_BOAT", "SPRUCE_BUTTON", "SPRUCE_DOOR", "SPRUCE_FENCE", "SPRUCE_FENCE_GATE", "SPRUCE_LEAVES", "SPRUCE_LOG", "SPRUCE_PLANKS", "SPRUCE_PRESSURE_PLATE", "SPRUCE_SAPLING", "SPRUCE_SIGN", "SPRUCE_SLAB", "SPRUCE_STAIRS", "SPRUCE_TRAPDOOR", "SPRUCE_WALL_SIGN", "SPRUCE_WOOD", "SPYGLASS", "SQUID_SPAWN_EGG", "STICK", "STICKY_PISTON", "STONE", "STONE_AXE", "STONE_BRICK_SLAB", "STONE_BRICK_STAIRS", "STONE_BRICK_WALL", "STONE_BRICKS", "STONE_BUTTON", "STONE_HOE", "STONE_PICKAXE", "STONE_PRESSURE_PLATE", "STONE_SHOVEL", "STONE_SLAB", "STONE_STAIRS", "STONE_SWORD", "STONECUTTER", "STRAY_SPAWN_EGG", "STRIDER_SPAWN_EGG", "STRING", "STRIPPED_ACACIA_LOG", "STRIPPED_ACACIA_WOOD", "STRIPPED_BIRCH_LOG", "STRIPPED_BIRCH_WOOD", "STRIPPED_CRIMSON_HYPHAE", "STRIPPED_CRIMSON_STEM", "STRIPPED_DARK_OAK_LOG", "STRIPPED_DARK_OAK_WOOD", "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD", "STRIPPED_OAK_LOG", "STRIPPED_OAK_WOOD", "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD", "STRIPPED_WARPED_HYPHAE", "STRIPPED_WARPED_STEM", "STRUCTURE_BLOCK", "STRUCTURE_VOID", "SUGAR", "SUGAR_CANE", "SUNFLOWER", "SUSPICIOUS_STEW", "SWEET_BERRIES", "SWEET_BERRY_BUSH", "TALL_GRASS", "TALL_SEAGRASS", "TARGET", "TERRACOTTA", "TINTED_GLASS", "TIPPED_ARROW", "TNT", "TNT_MINECART", "TORCH", "TOTEM_OF_UNDYING", "TRADER_LLAMA_SPAWN_EGG", "TRAPPED_CHEST", "TRIDENT", "TRIPWIRE", "TRIPWIRE_HOOK", "TROPICAL_FISH", "TROPICAL_FISH_BUCKET", "TROPICAL_FISH_SPAWN_EGG", "TUBE_CORAL", "TUBE_CORAL_BLOCK", "TUBE_CORAL_FAN", "TUBE_CORAL_WALL_FAN", "TUFF", "TURTLE_EGG", "TURTLE_HELMET", "TURTLE_SPAWN_EGG", "TWISTING_VINES", "TWISTING_VINES_PLANT", "VEX_SPAWN_EGG", "VILLAGER_SPAWN_EGG", "VINDICATOR_SPAWN_EGG", "VINE", "VOID_AIR", "WALL_TORCH", "WANDERING_TRADER_SPAWN_EGG", "WARPED_BUTTON", "WARPED_DOOR", "WARPED_FENCE", "WARPED_FENCE_GATE", "WARPED_FUNGUS", "WARPED_FUNGUS_ON_A_STICK", "WARPED_HYPHAE", "WARPED_NYLIUM", "WARPED_PLANKS", "WARPED_PRESSURE_PLATE", "WARPED_ROOTS", "WARPED_SIGN", "WARPED_SLAB", "WARPED_STAIRS", "WARPED_STEM", "WARPED_TRAPDOOR", "WARPED_WALL_SIGN", "WARPED_WART_BLOCK", "WATER", "WATER_BUCKET", "WATER_CAULDRON", "WAXED_COPPER_BLOCK", "WAXED_CUT_COPPER", "WAXED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_COPPER", "WAXED_EXPOSED_CUT_COPPER", "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_COPPER", "WAXED_OXIDIZED_CUT_COPPER", "WAXED_OXIDIZED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_COPPER", "WAXED_WEATHERED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_STAIRS", "WEATHERED_COPPER", "WEATHERED_CUT_COPPER", "WEATHERED_CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_STAIRS", "WEEPING_VINES", "WEEPING_VINES_PLANT", "WET_SPONGE", "WHEAT", "WHEAT_SEEDS", "WHITE_BANNER", "WHITE_BED", "WHITE_CANDLE", "WHITE_CANDLE_CAKE", "WHITE_CARPET", "WHITE_CONCRETE", "WHITE_CONCRETE_POWDER", "WHITE_DYE", "WHITE_GLAZED_TERRACOTTA", "WHITE_SHULKER_BOX", "WHITE_STAINED_GLASS", "WHITE_STAINED_GLASS_PANE", "WHITE_TERRACOTTA", "WHITE_TULIP", "WHITE_WALL_BANNER", "WHITE_WOOL", "WITCH_SPAWN_EGG", "WITHER_ROSE", "WITHER_SKELETON_SKULL", "WITHER_SKELETON_SPAWN_EGG", "WITHER_SKELETON_WALL_SKULL", "WOLF_SPAWN_EGG", "WOODEN_AXE", "WOODEN_HOE", "WOODEN_PICKAXE", "WOODEN_SHOVEL", "WOODEN_SWORD", "WRITABLE_BOOK", "WRITTEN_BOOK", "YELLOW_BANNER", "YELLOW_BED", "YELLOW_CANDLE", "YELLOW_CANDLE_CAKE", "YELLOW_CARPET", "YELLOW_CONCRETE", "YELLOW_CONCRETE_POWDER", "YELLOW_DYE", "YELLOW_GLAZED_TERRACOTTA", "YELLOW_SHULKER_BOX", "YELLOW_STAINED_GLASS", "YELLOW_STAINED_GLASS_PANE", "YELLOW_TERRACOTTA", "YELLOW_WALL_BANNER", "YELLOW_WOOL", "ZOGLIN_SPAWN_EGG", "ZOMBIE_HEAD", "ZOMBIE_HORSE_SPAWN_EGG", "ZOMBIE_SPAWN_EGG", "ZOMBIE_VILLAGER_SPAWN_EGG", "ZOMBIE_WALL_HEAD", "ZOMBIFIED_PIGLIN_SPAWN_EGG"]

const enchantmentAPINames = ["ARROW_DAMAGE", "ARROW_FIRE", "ARROW_INFINITE", "ARROW_KNOCKBACK", "BINDING_CURSE", "CHANNELING", "DAMAGE_ALL", "DAMAGE_ARTHROPODS", "DAMAGE_UNDEAD", "DEPTH_STRIDER", "DIG_SPEED", "DURABILITY", "FIRE_ASPECT", "FROST_WALKER", "IMPALING", "KNOCKBACK", "LOOT_BONUS_BLOCKS", "LOOT_BONUS_MOBS", "LOYALTY", "LUCK", "LURE", "MENDING", "MULTISHOT", "OXYGEN", "PIERCING", "PROTECTION_ENVIRONMENTAL", "PROTECTION_EXPLOSIONS", "PROTECTION_FALL", "PROTECTION_FIRE", "PROTECTION_PROJECTILE", "QUICK_CHARGE", "RIPTIDE", "SILK_TOUCH", "SOUL_SPEED", "SWEEPING_EDGE", "THORNS", "VANISHING_CURSE", "WATER_WORKER"]

const potionEffectsAPINames = ["AWKWARD", "FIRE_RESISTANCE", "INSTANT_DAMAGE", "INSTANT_HEAL", "INVISIBILITY", "JUMP", "LUCK", "MUNDANE", "NIGHT_VISION", "POISON", "REGEN", "SLOW_FALLING", "SLOWNESS", "SPEED", "STRENGTH", "THICK", "TURTLE_MASTER", "UNCRAFTABLE", "WATER", "WATER_BREATHING", "WEAKNESS"]

const entityTypeAPINames = ["AREA_EFFECT_CLOUD", "ARMOR_STAND", "ARROW", "AXOLOTL", "BAT", "BEE", "BLAZE", "BOAT", "CAT", "CAVE_SPIDER", "CHICKEN", "COD", "COW", "CREEPER", "DOLPHIN", "DONKEY", "DRAGON_FIREBALL", "DROPPED_ITEM", "DROWNED", "EGG", "ELDER_GUARDIAN", "ENDER_CRYSTAL", "ENDER_DRAGON", "ENDER_PEARL", "ENDER_SIGNAL", "ENDERMAN", "ENDERMITE", "EVOKER", "EVOKER_FANGS", "EXPERIENCE_ORB", "FALLING_BLOCK", "FIREBALL", "FIREWORK", "FISHING_HOOK", "FOX", "GHAST", "GIANT", "GLOW_ITEM_FRAME", "GLOW_SQUID", "GOAT", "GUARDIAN", "HOGLIN", "HORSE", "HUSK", "ILLUSIONER", "IRON_GOLEM", "ITEM_FRAME", "LEASH_HITCH", "LIGHTNING", "LLAMA", "LLAMA_SPIT", "MAGMA_CUBE", "MARKER", "MINECART", "MINECART_CHEST", "MINECART_COMMAND", "MINECART_FURNACE", "MINECART_HOPPER", "MINECART_MOB_SPAWNER", "MINECART_TNT", "MULE", "MUSHROOM_COW", "OCELOT", "PAINTING", "PANDA", "PARROT", "PHANTOM", "PIG", "PIGLIN", "PIGLIN_BRUTE", "PILLAGER", "PLAYER", "POLAR_BEAR", "PRIMED_TNT", "PUFFERFISH", "RABBIT", "RAVAGER", "SALMON", "SHEEP", "SHULKER", "SHULKER_BULLET", "SILVERFISH", "SKELETON", "SKELETON_HORSE", "SLIME", "SMALL_FIREBALL", "SNOWBALL", "SNOWMAN", "SPECTRAL_ARROW", "SPIDER", "SPLASH_POTION", "SQUID", "STRAY", "STRIDER", "THROWN_EXP_BOTTLE", "TRADER_LLAMA", "TRIDENT", "TROPICAL_FISH", "TURTLE", "UNKNOWN", "VEX", "VILLAGER", "VINDICATOR", "WANDERING_TRADER", "WITCH", "WITHER", "WITHER_SKELETON", "WITHER_SKULL", "WOLF", "ZOGLIN", "ZOMBIE", "ZOMBIE_HORSE", "ZOMBIE_VILLAGER", "ZOMBIFIED_PIGLIN"]

const powerAPINames = ["arrow_fireworks.yml", "arrow_rain.yml", "attack_arrow.yml", "attack_blinding.yml", "attack_confusing.yml", "attack_fire.yml", "attack_fireball.yml", "attack_freeze.yml", "attack_gravity.yml", "attack_lightning.yml", "attack_poison.yml", "attack_push.yml", "attack_vacuum.yml", "attack_weakness.yml", "attack_web.yml", "attack_wither.yml", "bonus_coins.yml", "bonus_loot.yml", "bullet_hell.yml", "channel_healing.yml", "corpse.yml", "death_slice.yml", "ender_dragon_aimed_fireball.yml", "ender_dragon_arrow_bombardment.yml", "ender_dragon_disco_fireballs.yml", "ender_dragon_empowered_lightning.yml", "ender_dragon_ender_fireball_bombardment.yml", "ender_dragon_endermite_bombardment.yml", "ender_dragon_fireball_bombardment.yml", "ender_dragon_potion_bombardment.yml", "ender_dragon_shockwave.yml", "ender_dragon_tornado.yml", "firestorm.yml", "fireworks_barrage.yml", "flame_pyre.yml", "flamethrower.yml", "frost_cone.yml", "gold_explosion.yml", "gold_shotgun.yml", "ground_pound.yml", "hyper_loot.yml", "implosion.yml", "invisibility.yml", "invulnerability_arrow.yml", "invulnerability_fall_damage.yml", "invulnerability_fire.yml", "invulnerability_knockback.yml", "lightning_bolts.yml", "meteor_shower.yml", "moonwalk.yml", "movement_speed.yml", "photon_ray.yml", "plasma_blaster.yml", "shield_wall.yml", "skeleton_pillar.yml", "skeleton_tracking_arrow.yml", "spirit_walk.yml", "summon_embers.yml", "summon_the_returned.yml", "taunt.yml", "thunderstorm.yml", "tracking_fireball.yml", "zombie_bloat.yml", "zombie_friends.yml", "zombie_necronomicon.yml", "zombie_parents.yml"]

//This is a combination of particles and materials
const trailAPINames = ["ACACIA_BOAT", "ACACIA_BUTTON", "ACACIA_DOOR", "ACACIA_FENCE", "ACACIA_FENCE_GATE", "ACACIA_LEAVES", "ACACIA_LOG", "ACACIA_PLANKS", "ACACIA_PRESSURE_PLATE", "ACACIA_SAPLING", "ACACIA_SIGN", "ACACIA_SLAB", "ACACIA_STAIRS", "ACACIA_TRAPDOOR", "ACACIA_WALL_SIGN", "ACACIA_WOOD", "ACTIVATOR_RAIL", "AIR", "ALLIUM", "AMETHYST_BLOCK", "AMETHYST_CLUSTER", "AMETHYST_SHARD", "ANCIENT_DEBRIS", "ANDESITE", "ANDESITE_SLAB", "ANDESITE_STAIRS", "ANDESITE_WALL", "ANVIL", "APPLE", "ARMOR_STAND", "ARROW", "ATTACHED_MELON_STEM", "ATTACHED_PUMPKIN_STEM", "AXOLOTL_BUCKET", "AXOLOTL_SPAWN_EGG", "AZALEA", "AZALEA_LEAVES", "AZURE_BLUET", "BAKED_POTATO", "BAMBOO", "BAMBOO_SAPLING", "BARREL", "BARRIER", "BASALT", "BAT_SPAWN_EGG", "BEACON", "BEDROCK", "BEE_NEST", "BEE_SPAWN_EGG", "BEEF", "BEEHIVE", "BEETROOT", "BEETROOT_SEEDS", "BEETROOT_SOUP", "BEETROOTS", "BELL", "BIG_DRIPLEAF", "BIG_DRIPLEAF_STEM", "BIRCH_BOAT", "BIRCH_BUTTON", "BIRCH_DOOR", "BIRCH_FENCE", "BIRCH_FENCE_GATE", "BIRCH_LEAVES", "BIRCH_LOG", "BIRCH_PLANKS", "BIRCH_PRESSURE_PLATE", "BIRCH_SAPLING", "BIRCH_SIGN", "BIRCH_SLAB", "BIRCH_STAIRS", "BIRCH_TRAPDOOR", "BIRCH_WALL_SIGN", "BIRCH_WOOD", "BLACK_BANNER", "BLACK_BED", "BLACK_CANDLE", "BLACK_CANDLE_CAKE", "BLACK_CARPET", "BLACK_CONCRETE", "BLACK_CONCRETE_POWDER", "BLACK_DYE", "BLACK_GLAZED_TERRACOTTA", "BLACK_SHULKER_BOX", "BLACK_STAINED_GLASS", "BLACK_STAINED_GLASS_PANE", "BLACK_TERRACOTTA", "BLACK_WALL_BANNER", "BLACK_WOOL", "BLACKSTONE", "BLACKSTONE_SLAB", "BLACKSTONE_STAIRS", "BLACKSTONE_WALL", "BLAST_FURNACE", "BLAZE_POWDER", "BLAZE_ROD", "BLAZE_SPAWN_EGG", "BLUE_BANNER", "BLUE_BED", "BLUE_CANDLE", "BLUE_CANDLE_CAKE", "BLUE_CARPET", "BLUE_CONCRETE", "BLUE_CONCRETE_POWDER", "BLUE_DYE", "BLUE_GLAZED_TERRACOTTA", "BLUE_ICE", "BLUE_ORCHID", "BLUE_SHULKER_BOX", "BLUE_STAINED_GLASS", "BLUE_STAINED_GLASS_PANE", "BLUE_TERRACOTTA", "BLUE_WALL_BANNER", "BLUE_WOOL", "BONE", "BONE_BLOCK", "BONE_MEAL", "BOOK", "BOOKSHELF", "BOW", "BOWL", "BRAIN_CORAL", "BRAIN_CORAL_BLOCK", "BRAIN_CORAL_FAN", "BRAIN_CORAL_WALL_FAN", "BREAD", "BREWING_STAND", "BRICK", "BRICK_SLAB", "BRICK_STAIRS", "BRICK_WALL", "BRICKS", "BROWN_BANNER", "BROWN_BED", "BROWN_CANDLE", "BROWN_CANDLE_CAKE", "BROWN_CARPET", "BROWN_CONCRETE", "BROWN_CONCRETE_POWDER", "BROWN_DYE", "BROWN_GLAZED_TERRACOTTA", "BROWN_MUSHROOM", "BROWN_MUSHROOM_BLOCK", "BROWN_SHULKER_BOX", "BROWN_STAINED_GLASS", "BROWN_STAINED_GLASS_PANE", "BROWN_TERRACOTTA", "BROWN_WALL_BANNER", "BROWN_WOOL", "BUBBLE_COLUMN", "BUBBLE_CORAL", "BUBBLE_CORAL_BLOCK", "BUBBLE_CORAL_FAN", "BUBBLE_CORAL_WALL_FAN", "BUCKET", "BUDDING_AMETHYST", "BUNDLE", "CACTUS", "CAKE", "CALCITE", "CAMPFIRE", "CANDLE", "CANDLE_CAKE", "CARROT", "CARROT_ON_A_STICK", "CARROTS", "CARTOGRAPHY_TABLE", "CARVED_PUMPKIN", "CAT_SPAWN_EGG", "CAULDRON", "CAVE_AIR", "CAVE_SPIDER_SPAWN_EGG", "CAVE_VINES", "CAVE_VINES_PLANT", "CHAIN", "CHAIN_COMMAND_BLOCK", "CHAINMAIL_BOOTS", "CHAINMAIL_CHESTPLATE", "CHAINMAIL_HELMET", "CHAINMAIL_LEGGINGS", "CHARCOAL", "CHEST", "CHEST_MINECART", "CHICKEN", "CHICKEN_SPAWN_EGG", "CHIPPED_ANVIL", "CHISELED_DEEPSLATE", "CHISELED_NETHER_BRICKS", "CHISELED_POLISHED_BLACKSTONE", "CHISELED_QUARTZ_BLOCK", "CHISELED_RED_SANDSTONE", "CHISELED_SANDSTONE", "CHISELED_STONE_BRICKS", "CHORUS_FLOWER", "CHORUS_FRUIT", "CHORUS_PLANT", "CLAY", "CLAY_BALL", "CLOCK", "COAL", "COAL_BLOCK", "COAL_ORE", "COARSE_DIRT", "COBBLED_DEEPSLATE", "COBBLED_DEEPSLATE_SLAB", "COBBLED_DEEPSLATE_STAIRS", "COBBLED_DEEPSLATE_WALL", "COBBLESTONE", "COBBLESTONE_SLAB", "COBBLESTONE_STAIRS", "COBBLESTONE_WALL", "COBWEB", "COCOA", "COCOA_BEANS", "COD", "COD_BUCKET", "COD_SPAWN_EGG", "COMMAND_BLOCK", "COMMAND_BLOCK_MINECART", "COMPARATOR", "COMPASS", "COMPOSTER", "CONDUIT", "COOKED_BEEF", "COOKED_CHICKEN", "COOKED_COD", "COOKED_MUTTON", "COOKED_PORKCHOP", "COOKED_RABBIT", "COOKED_SALMON", "COOKIE", "COPPER_BLOCK", "COPPER_INGOT", "COPPER_ORE", "CORNFLOWER", "COW_SPAWN_EGG", "CRACKED_DEEPSLATE_BRICKS", "CRACKED_DEEPSLATE_TILES", "CRACKED_NETHER_BRICKS", "CRACKED_POLISHED_BLACKSTONE_BRICKS", "CRACKED_STONE_BRICKS", "CRAFTING_TABLE", "CREEPER_BANNER_PATTERN", "CREEPER_HEAD", "CREEPER_SPAWN_EGG", "CREEPER_WALL_HEAD", "CRIMSON_BUTTON", "CRIMSON_DOOR", "CRIMSON_FENCE", "CRIMSON_FENCE_GATE", "CRIMSON_FUNGUS", "CRIMSON_HYPHAE", "CRIMSON_NYLIUM", "CRIMSON_PLANKS", "CRIMSON_PRESSURE_PLATE", "CRIMSON_ROOTS", "CRIMSON_SIGN", "CRIMSON_SLAB", "CRIMSON_STAIRS", "CRIMSON_STEM", "CRIMSON_TRAPDOOR", "CRIMSON_WALL_SIGN", "CROSSBOW", "CRYING_OBSIDIAN", "CUT_COPPER", "CUT_COPPER_SLAB", "CUT_COPPER_STAIRS", "CUT_RED_SANDSTONE", "CUT_RED_SANDSTONE_SLAB", "CUT_SANDSTONE", "CUT_SANDSTONE_SLAB", "CYAN_BANNER", "CYAN_BED", "CYAN_CANDLE", "CYAN_CANDLE_CAKE", "CYAN_CARPET", "CYAN_CONCRETE", "CYAN_CONCRETE_POWDER", "CYAN_DYE", "CYAN_GLAZED_TERRACOTTA", "CYAN_SHULKER_BOX", "CYAN_STAINED_GLASS", "CYAN_STAINED_GLASS_PANE", "CYAN_TERRACOTTA", "CYAN_WALL_BANNER", "CYAN_WOOL", "DAMAGED_ANVIL", "DANDELION", "DARK_OAK_BOAT", "DARK_OAK_BUTTON", "DARK_OAK_DOOR", "DARK_OAK_FENCE", "DARK_OAK_FENCE_GATE", "DARK_OAK_LEAVES", "DARK_OAK_LOG", "DARK_OAK_PLANKS", "DARK_OAK_PRESSURE_PLATE", "DARK_OAK_SAPLING", "DARK_OAK_SIGN", "DARK_OAK_SLAB", "DARK_OAK_STAIRS", "DARK_OAK_TRAPDOOR", "DARK_OAK_WALL_SIGN", "DARK_OAK_WOOD", "DARK_PRISMARINE", "DARK_PRISMARINE_SLAB", "DARK_PRISMARINE_STAIRS", "DAYLIGHT_DETECTOR", "DEAD_BRAIN_CORAL", "DEAD_BRAIN_CORAL_BLOCK", "DEAD_BRAIN_CORAL_FAN", "DEAD_BRAIN_CORAL_WALL_FAN", "DEAD_BUBBLE_CORAL", "DEAD_BUBBLE_CORAL_BLOCK", "DEAD_BUBBLE_CORAL_FAN", "DEAD_BUBBLE_CORAL_WALL_FAN", "DEAD_BUSH", "DEAD_FIRE_CORAL", "DEAD_FIRE_CORAL_BLOCK", "DEAD_FIRE_CORAL_FAN", "DEAD_FIRE_CORAL_WALL_FAN", "DEAD_HORN_CORAL", "DEAD_HORN_CORAL_BLOCK", "DEAD_HORN_CORAL_FAN", "DEAD_HORN_CORAL_WALL_FAN", "DEAD_TUBE_CORAL", "DEAD_TUBE_CORAL_BLOCK", "DEAD_TUBE_CORAL_FAN", "DEAD_TUBE_CORAL_WALL_FAN", "DEBUG_STICK", "DEEPSLATE", "DEEPSLATE_BRICK_SLAB", "DEEPSLATE_BRICK_STAIRS", "DEEPSLATE_BRICK_WALL", "DEEPSLATE_BRICKS", "DEEPSLATE_COAL_ORE", "DEEPSLATE_COPPER_ORE", "DEEPSLATE_DIAMOND_ORE", "DEEPSLATE_EMERALD_ORE", "DEEPSLATE_GOLD_ORE", "DEEPSLATE_IRON_ORE", "DEEPSLATE_LAPIS_ORE", "DEEPSLATE_REDSTONE_ORE", "DEEPSLATE_TILE_SLAB", "DEEPSLATE_TILE_STAIRS", "DEEPSLATE_TILE_WALL", "DEEPSLATE_TILES", "DETECTOR_RAIL", "DIAMOND", "DIAMOND_AXE", "DIAMOND_BLOCK", "DIAMOND_BOOTS", "DIAMOND_CHESTPLATE", "DIAMOND_HELMET", "DIAMOND_HOE", "DIAMOND_HORSE_ARMOR", "DIAMOND_LEGGINGS", "DIAMOND_ORE", "DIAMOND_PICKAXE", "DIAMOND_SHOVEL", "DIAMOND_SWORD", "DIORITE", "DIORITE_SLAB", "DIORITE_STAIRS", "DIORITE_WALL", "DIRT", "DIRT_PATH", "DISPENSER", "DOLPHIN_SPAWN_EGG", "DONKEY_SPAWN_EGG", "DRAGON_BREATH", "DRAGON_EGG", "DRAGON_HEAD", "DRAGON_WALL_HEAD", "DRIED_KELP", "DRIED_KELP_BLOCK", "DRIPSTONE_BLOCK", "DROPPER", "DROWNED_SPAWN_EGG", "EGG", "ELDER_GUARDIAN_SPAWN_EGG", "ELYTRA", "EMERALD", "EMERALD_BLOCK", "EMERALD_ORE", "ENCHANTED_BOOK", "ENCHANTED_GOLDEN_APPLE", "ENCHANTING_TABLE", "END_CRYSTAL", "END_GATEWAY", "END_PORTAL", "END_PORTAL_FRAME", "END_ROD", "END_STONE", "END_STONE_BRICK_SLAB", "END_STONE_BRICK_STAIRS", "END_STONE_BRICK_WALL", "END_STONE_BRICKS", "ENDER_CHEST", "ENDER_EYE", "ENDER_PEARL", "ENDERMAN_SPAWN_EGG", "ENDERMITE_SPAWN_EGG", "EVOKER_SPAWN_EGG", "EXPERIENCE_BOTTLE", "EXPOSED_COPPER", "EXPOSED_CUT_COPPER", "EXPOSED_CUT_COPPER_SLAB", "EXPOSED_CUT_COPPER_STAIRS", "FARMLAND", "FEATHER", "FERMENTED_SPIDER_EYE", "FERN", "FILLED_MAP", "FIRE", "FIRE_CHARGE", "FIRE_CORAL", "FIRE_CORAL_BLOCK", "FIRE_CORAL_FAN", "FIRE_CORAL_WALL_FAN", "FIREWORK_ROCKET", "FIREWORK_STAR", "FISHING_ROD", "FLETCHING_TABLE", "FLINT", "FLINT_AND_STEEL", "FLOWER_BANNER_PATTERN", "FLOWER_POT", "FLOWERING_AZALEA", "FLOWERING_AZALEA_LEAVES", "FOX_SPAWN_EGG", "FROSTED_ICE", "FURNACE", "FURNACE_MINECART", "GHAST_SPAWN_EGG", "GHAST_TEAR", "GILDED_BLACKSTONE", "GLASS", "GLASS_BOTTLE", "GLASS_PANE", "GLISTERING_MELON_SLICE", "GLOBE_BANNER_PATTERN", "GLOW_BERRIES", "GLOW_INK_SAC", "GLOW_ITEM_FRAME", "GLOW_LICHEN", "GLOW_SQUID_SPAWN_EGG", "GLOWSTONE", "GLOWSTONE_DUST", "GOAT_SPAWN_EGG", "GOLD_BLOCK", "GOLD_INGOT", "GOLD_NUGGET", "GOLD_ORE", "GOLDEN_APPLE", "GOLDEN_AXE", "GOLDEN_BOOTS", "GOLDEN_CARROT", "GOLDEN_CHESTPLATE", "GOLDEN_HELMET", "GOLDEN_HOE", "GOLDEN_HORSE_ARMOR", "GOLDEN_LEGGINGS", "GOLDEN_PICKAXE", "GOLDEN_SHOVEL", "GOLDEN_SWORD", "GRANITE", "GRANITE_SLAB", "GRANITE_STAIRS", "GRANITE_WALL", "GRASS", "GRASS_BLOCK", "GRAVEL", "GRAY_BANNER", "GRAY_BED", "GRAY_CANDLE", "GRAY_CANDLE_CAKE", "GRAY_CARPET", "GRAY_CONCRETE", "GRAY_CONCRETE_POWDER", "GRAY_DYE", "GRAY_GLAZED_TERRACOTTA", "GRAY_SHULKER_BOX", "GRAY_STAINED_GLASS", "GRAY_STAINED_GLASS_PANE", "GRAY_TERRACOTTA", "GRAY_WALL_BANNER", "GRAY_WOOL", "GREEN_BANNER", "GREEN_BED", "GREEN_CANDLE", "GREEN_CANDLE_CAKE", "GREEN_CARPET", "GREEN_CONCRETE", "GREEN_CONCRETE_POWDER", "GREEN_DYE", "GREEN_GLAZED_TERRACOTTA", "GREEN_SHULKER_BOX", "GREEN_STAINED_GLASS", "GREEN_STAINED_GLASS_PANE", "GREEN_TERRACOTTA", "GREEN_WALL_BANNER", "GREEN_WOOL", "GRINDSTONE", "GUARDIAN_SPAWN_EGG", "GUNPOWDER", "HANGING_ROOTS", "HAY_BLOCK", "HEART_OF_THE_SEA", "HEAVY_WEIGHTED_PRESSURE_PLATE", "HOGLIN_SPAWN_EGG", "HONEY_BLOCK", "HONEY_BOTTLE", "HONEYCOMB", "HONEYCOMB_BLOCK", "HOPPER", "HOPPER_MINECART", "HORN_CORAL", "HORN_CORAL_BLOCK", "HORN_CORAL_FAN", "HORN_CORAL_WALL_FAN", "HORSE_SPAWN_EGG", "HUSK_SPAWN_EGG", "ICE", "INFESTED_CHISELED_STONE_BRICKS", "INFESTED_COBBLESTONE", "INFESTED_CRACKED_STONE_BRICKS", "INFESTED_DEEPSLATE", "INFESTED_MOSSY_STONE_BRICKS", "INFESTED_STONE", "INFESTED_STONE_BRICKS", "INK_SAC", "IRON_AXE", "IRON_BARS", "IRON_BLOCK", "IRON_BOOTS", "IRON_CHESTPLATE", "IRON_DOOR", "IRON_HELMET", "IRON_HOE", "IRON_HORSE_ARMOR", "IRON_INGOT", "IRON_LEGGINGS", "IRON_NUGGET", "IRON_ORE", "IRON_PICKAXE", "IRON_SHOVEL", "IRON_SWORD", "IRON_TRAPDOOR", "ITEM_FRAME", "JACK_O_LANTERN", "JIGSAW", "JUKEBOX", "JUNGLE_BOAT", "JUNGLE_BUTTON", "JUNGLE_DOOR", "JUNGLE_FENCE", "JUNGLE_FENCE_GATE", "JUNGLE_LEAVES", "JUNGLE_LOG", "JUNGLE_PLANKS", "JUNGLE_PRESSURE_PLATE", "JUNGLE_SAPLING", "JUNGLE_SIGN", "JUNGLE_SLAB", "JUNGLE_STAIRS", "JUNGLE_TRAPDOOR", "JUNGLE_WALL_SIGN", "JUNGLE_WOOD", "KELP", "KELP_PLANT", "KNOWLEDGE_BOOK", "LADDER", "LANTERN", "LAPIS_BLOCK", "LAPIS_LAZULI", "LAPIS_ORE", "LARGE_AMETHYST_BUD", "LARGE_FERN", "LAVA", "LAVA_BUCKET", "LAVA_CAULDRON", "LEAD", "LEATHER", "LEATHER_BOOTS", "LEATHER_CHESTPLATE", "LEATHER_HELMET", "LEATHER_HORSE_ARMOR", "LEATHER_LEGGINGS", "LECTERN", "LEVER", "LIGHT", "LIGHT_BLUE_BANNER", "LIGHT_BLUE_BED", "LIGHT_BLUE_CANDLE", "LIGHT_BLUE_CANDLE_CAKE", "LIGHT_BLUE_CARPET", "LIGHT_BLUE_CONCRETE", "LIGHT_BLUE_CONCRETE_POWDER", "LIGHT_BLUE_DYE", "LIGHT_BLUE_GLAZED_TERRACOTTA", "LIGHT_BLUE_SHULKER_BOX", "LIGHT_BLUE_STAINED_GLASS", "LIGHT_BLUE_STAINED_GLASS_PANE", "LIGHT_BLUE_TERRACOTTA", "LIGHT_BLUE_WALL_BANNER", "LIGHT_BLUE_WOOL", "LIGHT_GRAY_BANNER", "LIGHT_GRAY_BED", "LIGHT_GRAY_CANDLE", "LIGHT_GRAY_CANDLE_CAKE", "LIGHT_GRAY_CARPET", "LIGHT_GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE_POWDER", "LIGHT_GRAY_DYE", "LIGHT_GRAY_GLAZED_TERRACOTTA", "LIGHT_GRAY_SHULKER_BOX", "LIGHT_GRAY_STAINED_GLASS", "LIGHT_GRAY_STAINED_GLASS_PANE", "LIGHT_GRAY_TERRACOTTA", "LIGHT_GRAY_WALL_BANNER", "LIGHT_GRAY_WOOL", "LIGHT_WEIGHTED_PRESSURE_PLATE", "LIGHTNING_ROD", "LILAC", "LILY_OF_THE_VALLEY", "LILY_PAD", "LIME_BANNER", "LIME_BED", "LIME_CANDLE", "LIME_CANDLE_CAKE", "LIME_CARPET", "LIME_CONCRETE", "LIME_CONCRETE_POWDER", "LIME_DYE", "LIME_GLAZED_TERRACOTTA", "LIME_SHULKER_BOX", "LIME_STAINED_GLASS", "LIME_STAINED_GLASS_PANE", "LIME_TERRACOTTA", "LIME_WALL_BANNER", "LIME_WOOL", "LINGERING_POTION", "LLAMA_SPAWN_EGG", "LODESTONE", "LOOM", "MAGENTA_BANNER", "MAGENTA_BED", "MAGENTA_CANDLE", "MAGENTA_CANDLE_CAKE", "MAGENTA_CARPET", "MAGENTA_CONCRETE", "MAGENTA_CONCRETE_POWDER", "MAGENTA_DYE", "MAGENTA_GLAZED_TERRACOTTA", "MAGENTA_SHULKER_BOX", "MAGENTA_STAINED_GLASS", "MAGENTA_STAINED_GLASS_PANE", "MAGENTA_TERRACOTTA", "MAGENTA_WALL_BANNER", "MAGENTA_WOOL", "MAGMA_BLOCK", "MAGMA_CREAM", "MAGMA_CUBE_SPAWN_EGG", "MAP", "MEDIUM_AMETHYST_BUD", "MELON", "MELON_SEEDS", "MELON_SLICE", "MELON_STEM", "MILK_BUCKET", "MINECART", "MOJANG_BANNER_PATTERN", "MOOSHROOM_SPAWN_EGG", "MOSS_BLOCK", "MOSS_CARPET", "MOSSY_COBBLESTONE", "MOSSY_COBBLESTONE_SLAB", "MOSSY_COBBLESTONE_STAIRS", "MOSSY_COBBLESTONE_WALL", "MOSSY_STONE_BRICK_SLAB", "MOSSY_STONE_BRICK_STAIRS", "MOSSY_STONE_BRICK_WALL", "MOSSY_STONE_BRICKS", "MOVING_PISTON", "MULE_SPAWN_EGG", "MUSHROOM_STEM", "MUSHROOM_STEW", "MUSIC_DISC_11", "MUSIC_DISC_13", "MUSIC_DISC_BLOCKS", "MUSIC_DISC_CAT", "MUSIC_DISC_CHIRP", "MUSIC_DISC_FAR", "MUSIC_DISC_MALL", "MUSIC_DISC_MELLOHI", "MUSIC_DISC_OTHERSIDE", "MUSIC_DISC_PIGSTEP", "MUSIC_DISC_STAL", "MUSIC_DISC_STRAD", "MUSIC_DISC_WAIT", "MUSIC_DISC_WARD", "MUTTON", "MYCELIUM", "NAME_TAG", "NAUTILUS_SHELL", "NETHER_BRICK", "NETHER_BRICK_FENCE", "NETHER_BRICK_SLAB", "NETHER_BRICK_STAIRS", "NETHER_BRICK_WALL", "NETHER_BRICKS", "NETHER_GOLD_ORE", "NETHER_PORTAL", "NETHER_QUARTZ_ORE", "NETHER_SPROUTS", "NETHER_STAR", "NETHER_WART", "NETHER_WART_BLOCK", "NETHERITE_AXE", "NETHERITE_BLOCK", "NETHERITE_BOOTS", "NETHERITE_CHESTPLATE", "NETHERITE_HELMET", "NETHERITE_HOE", "NETHERITE_INGOT", "NETHERITE_LEGGINGS", "NETHERITE_PICKAXE", "NETHERITE_SCRAP", "NETHERITE_SHOVEL", "NETHERITE_SWORD", "NETHERRACK", "NOTE_BLOCK", "OAK_BOAT", "OAK_BUTTON", "OAK_DOOR", "OAK_FENCE", "OAK_FENCE_GATE", "OAK_LEAVES", "OAK_LOG", "OAK_PLANKS", "OAK_PRESSURE_PLATE", "OAK_SAPLING", "OAK_SIGN", "OAK_SLAB", "OAK_STAIRS", "OAK_TRAPDOOR", "OAK_WALL_SIGN", "OAK_WOOD", "OBSERVER", "OBSIDIAN", "OCELOT_SPAWN_EGG", "ORANGE_BANNER", "ORANGE_BED", "ORANGE_CANDLE", "ORANGE_CANDLE_CAKE", "ORANGE_CARPET", "ORANGE_CONCRETE", "ORANGE_CONCRETE_POWDER", "ORANGE_DYE", "ORANGE_GLAZED_TERRACOTTA", "ORANGE_SHULKER_BOX", "ORANGE_STAINED_GLASS", "ORANGE_STAINED_GLASS_PANE", "ORANGE_TERRACOTTA", "ORANGE_TULIP", "ORANGE_WALL_BANNER", "ORANGE_WOOL", "OXEYE_DAISY", "OXIDIZED_COPPER", "OXIDIZED_CUT_COPPER", "OXIDIZED_CUT_COPPER_SLAB", "OXIDIZED_CUT_COPPER_STAIRS", "PACKED_ICE", "PAINTING", "PANDA_SPAWN_EGG", "PAPER", "PARROT_SPAWN_EGG", "PEONY", "PETRIFIED_OAK_SLAB", "PHANTOM_MEMBRANE", "PHANTOM_SPAWN_EGG", "PIG_SPAWN_EGG", "PIGLIN_BANNER_PATTERN", "PIGLIN_BRUTE_SPAWN_EGG", "PIGLIN_SPAWN_EGG", "PILLAGER_SPAWN_EGG", "PINK_BANNER", "PINK_BED", "PINK_CANDLE", "PINK_CANDLE_CAKE", "PINK_CARPET", "PINK_CONCRETE", "PINK_CONCRETE_POWDER", "PINK_DYE", "PINK_GLAZED_TERRACOTTA", "PINK_SHULKER_BOX", "PINK_STAINED_GLASS", "PINK_STAINED_GLASS_PANE", "PINK_TERRACOTTA", "PINK_TULIP", "PINK_WALL_BANNER", "PINK_WOOL", "PISTON", "PISTON_HEAD", "PLAYER_HEAD", "PLAYER_WALL_HEAD", "PODZOL", "POINTED_DRIPSTONE", "POISONOUS_POTATO", "POLAR_BEAR_SPAWN_EGG", "POLISHED_ANDESITE", "POLISHED_ANDESITE_SLAB", "POLISHED_ANDESITE_STAIRS", "POLISHED_BASALT", "POLISHED_BLACKSTONE", "POLISHED_BLACKSTONE_BRICK_SLAB", "POLISHED_BLACKSTONE_BRICK_STAIRS", "POLISHED_BLACKSTONE_BRICK_WALL", "POLISHED_BLACKSTONE_BRICKS", "POLISHED_BLACKSTONE_BUTTON", "POLISHED_BLACKSTONE_PRESSURE_PLATE", "POLISHED_BLACKSTONE_SLAB", "POLISHED_BLACKSTONE_STAIRS", "POLISHED_BLACKSTONE_WALL", "POLISHED_DEEPSLATE", "POLISHED_DEEPSLATE_SLAB", "POLISHED_DEEPSLATE_STAIRS", "POLISHED_DEEPSLATE_WALL", "POLISHED_DIORITE", "POLISHED_DIORITE_SLAB", "POLISHED_DIORITE_STAIRS", "POLISHED_GRANITE", "POLISHED_GRANITE_SLAB", "POLISHED_GRANITE_STAIRS", "POPPED_CHORUS_FRUIT", "POPPY", "PORKCHOP", "POTATO", "POTATOES", "POTION", "POTTED_ACACIA_SAPLING", "POTTED_ALLIUM", "POTTED_AZALEA_BUSH", "POTTED_AZURE_BLUET", "POTTED_BAMBOO", "POTTED_BIRCH_SAPLING", "POTTED_BLUE_ORCHID", "POTTED_BROWN_MUSHROOM", "POTTED_CACTUS", "POTTED_CORNFLOWER", "POTTED_CRIMSON_FUNGUS", "POTTED_CRIMSON_ROOTS", "POTTED_DANDELION", "POTTED_DARK_OAK_SAPLING", "POTTED_DEAD_BUSH", "POTTED_FERN", "POTTED_FLOWERING_AZALEA_BUSH", "POTTED_JUNGLE_SAPLING", "POTTED_LILY_OF_THE_VALLEY", "POTTED_OAK_SAPLING", "POTTED_ORANGE_TULIP", "POTTED_OXEYE_DAISY", "POTTED_PINK_TULIP", "POTTED_POPPY", "POTTED_RED_MUSHROOM", "POTTED_RED_TULIP", "POTTED_SPRUCE_SAPLING", "POTTED_WARPED_FUNGUS", "POTTED_WARPED_ROOTS", "POTTED_WHITE_TULIP", "POTTED_WITHER_ROSE", "POWDER_SNOW", "POWDER_SNOW_BUCKET", "POWDER_SNOW_CAULDRON", "POWERED_RAIL", "PRISMARINE", "PRISMARINE_BRICK_SLAB", "PRISMARINE_BRICK_STAIRS", "PRISMARINE_BRICKS", "PRISMARINE_CRYSTALS", "PRISMARINE_SHARD", "PRISMARINE_SLAB", "PRISMARINE_STAIRS", "PRISMARINE_WALL", "PUFFERFISH", "PUFFERFISH_BUCKET", "PUFFERFISH_SPAWN_EGG", "PUMPKIN", "PUMPKIN_PIE", "PUMPKIN_SEEDS", "PUMPKIN_STEM", "PURPLE_BANNER", "PURPLE_BED", "PURPLE_CANDLE", "PURPLE_CANDLE_CAKE", "PURPLE_CARPET", "PURPLE_CONCRETE", "PURPLE_CONCRETE_POWDER", "PURPLE_DYE", "PURPLE_GLAZED_TERRACOTTA", "PURPLE_SHULKER_BOX", "PURPLE_STAINED_GLASS", "PURPLE_STAINED_GLASS_PANE", "PURPLE_TERRACOTTA", "PURPLE_WALL_BANNER", "PURPLE_WOOL", "PURPUR_BLOCK", "PURPUR_PILLAR", "PURPUR_SLAB", "PURPUR_STAIRS", "QUARTZ", "QUARTZ_BLOCK", "QUARTZ_BRICKS", "QUARTZ_PILLAR", "QUARTZ_SLAB", "QUARTZ_STAIRS", "RABBIT", "RABBIT_FOOT", "RABBIT_HIDE", "RABBIT_SPAWN_EGG", "RABBIT_STEW", "RAIL", "RAVAGER_SPAWN_EGG", "RAW_COPPER", "RAW_COPPER_BLOCK", "RAW_GOLD", "RAW_GOLD_BLOCK", "RAW_IRON", "RAW_IRON_BLOCK", "RED_BANNER", "RED_BED", "RED_CANDLE", "RED_CANDLE_CAKE", "RED_CARPET", "RED_CONCRETE", "RED_CONCRETE_POWDER", "RED_DYE", "RED_GLAZED_TERRACOTTA", "RED_MUSHROOM", "RED_MUSHROOM_BLOCK", "RED_NETHER_BRICK_SLAB", "RED_NETHER_BRICK_STAIRS", "RED_NETHER_BRICK_WALL", "RED_NETHER_BRICKS", "RED_SAND", "RED_SANDSTONE", "RED_SANDSTONE_SLAB", "RED_SANDSTONE_STAIRS", "RED_SANDSTONE_WALL", "RED_SHULKER_BOX", "RED_STAINED_GLASS", "RED_STAINED_GLASS_PANE", "RED_TERRACOTTA", "RED_TULIP", "RED_WALL_BANNER", "RED_WOOL", "REDSTONE", "REDSTONE_BLOCK", "REDSTONE_LAMP", "REDSTONE_ORE", "REDSTONE_TORCH", "REDSTONE_WALL_TORCH", "REDSTONE_WIRE", "REPEATER", "REPEATING_COMMAND_BLOCK", "RESPAWN_ANCHOR", "ROOTED_DIRT", "ROSE_BUSH", "ROTTEN_FLESH", "SADDLE", "SALMON", "SALMON_BUCKET", "SALMON_SPAWN_EGG", "SAND", "SANDSTONE", "SANDSTONE_SLAB", "SANDSTONE_STAIRS", "SANDSTONE_WALL", "SCAFFOLDING", "SCULK_SENSOR", "SCUTE", "SEA_LANTERN", "SEA_PICKLE", "SEAGRASS", "SHEARS", "SHEEP_SPAWN_EGG", "SHIELD", "SHROOMLIGHT", "SHULKER_BOX", "SHULKER_SHELL", "SHULKER_SPAWN_EGG", "SILVERFISH_SPAWN_EGG", "SKELETON_HORSE_SPAWN_EGG", "SKELETON_SKULL", "SKELETON_SPAWN_EGG", "SKELETON_WALL_SKULL", "SKULL_BANNER_PATTERN", "SLIME_BALL", "SLIME_BLOCK", "SLIME_SPAWN_EGG", "SMALL_AMETHYST_BUD", "SMALL_DRIPLEAF", "SMITHING_TABLE", "SMOKER", "SMOOTH_BASALT", "SMOOTH_QUARTZ", "SMOOTH_QUARTZ_SLAB", "SMOOTH_QUARTZ_STAIRS", "SMOOTH_RED_SANDSTONE", "SMOOTH_RED_SANDSTONE_SLAB", "SMOOTH_RED_SANDSTONE_STAIRS", "SMOOTH_SANDSTONE", "SMOOTH_SANDSTONE_SLAB", "SMOOTH_SANDSTONE_STAIRS", "SMOOTH_STONE", "SMOOTH_STONE_SLAB", "SNOW", "SNOW_BLOCK", "SNOWBALL", "SOUL_CAMPFIRE", "SOUL_FIRE", "SOUL_LANTERN", "SOUL_SAND", "SOUL_SOIL", "SOUL_TORCH", "SOUL_WALL_TORCH", "SPAWNER", "SPECTRAL_ARROW", "SPIDER_EYE", "SPIDER_SPAWN_EGG", "SPLASH_POTION", "SPONGE", "SPORE_BLOSSOM", "SPRUCE_BOAT", "SPRUCE_BUTTON", "SPRUCE_DOOR", "SPRUCE_FENCE", "SPRUCE_FENCE_GATE", "SPRUCE_LEAVES", "SPRUCE_LOG", "SPRUCE_PLANKS", "SPRUCE_PRESSURE_PLATE", "SPRUCE_SAPLING", "SPRUCE_SIGN", "SPRUCE_SLAB", "SPRUCE_STAIRS", "SPRUCE_TRAPDOOR", "SPRUCE_WALL_SIGN", "SPRUCE_WOOD", "SPYGLASS", "SQUID_SPAWN_EGG", "STICK", "STICKY_PISTON", "STONE", "STONE_AXE", "STONE_BRICK_SLAB", "STONE_BRICK_STAIRS", "STONE_BRICK_WALL", "STONE_BRICKS", "STONE_BUTTON", "STONE_HOE", "STONE_PICKAXE", "STONE_PRESSURE_PLATE", "STONE_SHOVEL", "STONE_SLAB", "STONE_STAIRS", "STONE_SWORD", "STONECUTTER", "STRAY_SPAWN_EGG", "STRIDER_SPAWN_EGG", "STRING", "STRIPPED_ACACIA_LOG", "STRIPPED_ACACIA_WOOD", "STRIPPED_BIRCH_LOG", "STRIPPED_BIRCH_WOOD", "STRIPPED_CRIMSON_HYPHAE", "STRIPPED_CRIMSON_STEM", "STRIPPED_DARK_OAK_LOG", "STRIPPED_DARK_OAK_WOOD", "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD", "STRIPPED_OAK_LOG", "STRIPPED_OAK_WOOD", "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD", "STRIPPED_WARPED_HYPHAE", "STRIPPED_WARPED_STEM", "STRUCTURE_BLOCK", "STRUCTURE_VOID", "SUGAR", "SUGAR_CANE", "SUNFLOWER", "SUSPICIOUS_STEW", "SWEET_BERRIES", "SWEET_BERRY_BUSH", "TALL_GRASS", "TALL_SEAGRASS", "TARGET", "TERRACOTTA", "TINTED_GLASS", "TIPPED_ARROW", "TNT", "TNT_MINECART", "TORCH", "TOTEM_OF_UNDYING", "TRADER_LLAMA_SPAWN_EGG", "TRAPPED_CHEST", "TRIDENT", "TRIPWIRE", "TRIPWIRE_HOOK", "TROPICAL_FISH", "TROPICAL_FISH_BUCKET", "TROPICAL_FISH_SPAWN_EGG", "TUBE_CORAL", "TUBE_CORAL_BLOCK", "TUBE_CORAL_FAN", "TUBE_CORAL_WALL_FAN", "TUFF", "TURTLE_EGG", "TURTLE_HELMET", "TURTLE_SPAWN_EGG", "TWISTING_VINES", "TWISTING_VINES_PLANT", "VEX_SPAWN_EGG", "VILLAGER_SPAWN_EGG", "VINDICATOR_SPAWN_EGG", "VINE", "VOID_AIR", "WALL_TORCH", "WANDERING_TRADER_SPAWN_EGG", "WARPED_BUTTON", "WARPED_DOOR", "WARPED_FENCE", "WARPED_FENCE_GATE", "WARPED_FUNGUS", "WARPED_FUNGUS_ON_A_STICK", "WARPED_HYPHAE", "WARPED_NYLIUM", "WARPED_PLANKS", "WARPED_PRESSURE_PLATE", "WARPED_ROOTS", "WARPED_SIGN", "WARPED_SLAB", "WARPED_STAIRS", "WARPED_STEM", "WARPED_TRAPDOOR", "WARPED_WALL_SIGN", "WARPED_WART_BLOCK", "WATER", "WATER_BUCKET", "WATER_CAULDRON", "WAXED_COPPER_BLOCK", "WAXED_CUT_COPPER", "WAXED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_COPPER", "WAXED_EXPOSED_CUT_COPPER", "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_COPPER", "WAXED_OXIDIZED_CUT_COPPER", "WAXED_OXIDIZED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_COPPER", "WAXED_WEATHERED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_STAIRS", "WEATHERED_COPPER", "WEATHERED_CUT_COPPER", "WEATHERED_CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_STAIRS", "WEEPING_VINES", "WEEPING_VINES_PLANT", "WET_SPONGE", "WHEAT", "WHEAT_SEEDS", "WHITE_BANNER", "WHITE_BED", "WHITE_CANDLE", "WHITE_CANDLE_CAKE", "WHITE_CARPET", "WHITE_CONCRETE", "WHITE_CONCRETE_POWDER", "WHITE_DYE", "WHITE_GLAZED_TERRACOTTA", "WHITE_SHULKER_BOX", "WHITE_STAINED_GLASS", "WHITE_STAINED_GLASS_PANE", "WHITE_TERRACOTTA", "WHITE_TULIP", "WHITE_WALL_BANNER", "WHITE_WOOL", "WITCH_SPAWN_EGG", "WITHER_ROSE", "WITHER_SKELETON_SKULL", "WITHER_SKELETON_SPAWN_EGG", "WITHER_SKELETON_WALL_SKULL", "WOLF_SPAWN_EGG", "WOODEN_AXE", "WOODEN_HOE", "WOODEN_PICKAXE", "WOODEN_SHOVEL", "WOODEN_SWORD", "WRITABLE_BOOK", "WRITTEN_BOOK", "YELLOW_BANNER", "YELLOW_BED", "YELLOW_CANDLE", "YELLOW_CANDLE_CAKE", "YELLOW_CARPET", "YELLOW_CONCRETE", "YELLOW_CONCRETE_POWDER", "YELLOW_DYE", "YELLOW_GLAZED_TERRACOTTA", "YELLOW_SHULKER_BOX", "YELLOW_STAINED_GLASS", "YELLOW_STAINED_GLASS_PANE", "YELLOW_TERRACOTTA", "YELLOW_WALL_BANNER", "YELLOW_WOOL", "ZOGLIN_SPAWN_EGG", "ZOMBIE_HEAD", "ZOMBIE_HORSE_SPAWN_EGG", "ZOMBIE_SPAWN_EGG", "ZOMBIE_VILLAGER_SPAWN_EGG", "ZOMBIE_WALL_HEAD", "ZOMBIFIED_PIGLIN_SPAWN_EGG", "ASH", "BLOCK_CRACK", "BLOCK_DUST", "BLOCK_MARKER", "BUBBLE_COLUMN_UP", "BUBBLE_POP", "CAMPFIRE_COSY_SMOKE", "CAMPFIRE_SIGNAL_SMOKE", "CLOUD", "COMPOSTER", "CRIMSON_SPORE", "CRIT", "CRIT_MAGIC", "CURRENT_DOWN", "DAMAGE_INDICATOR", "DOLPHIN", "DRAGON_BREATH", "DRIP_LAVA", "DRIP_WATER", "DRIPPING_DRIPSTONE_LAVA", "DRIPPING_DRIPSTONE_WATER", "DRIPPING_HONEY", "DRIPPING_OBSIDIAN_TEAR", "DUST_COLOR_TRANSITION", "ELECTRIC_SPARK", "ENCHANTMENT_TABLE", "END_ROD", "EXPLOSION_HUGE", "EXPLOSION_LARGE", "EXPLOSION_NORMAL", "FALLING_DRIPSTONE_LAVA", "FALLING_DRIPSTONE_WATER", "FALLING_DUST", "FALLING_HONEY", "FALLING_LAVA", "FALLING_NECTAR", "FALLING_OBSIDIAN_TEAR", "FALLING_SPORE_BLOSSOM", "FALLING_WATER", "FIREWORKS_SPARK", "FLAME", "FLASH", "GLOW", "GLOW_SQUID_INK", "HEART", "ITEM_CRACK", "LANDING_HONEY", "LANDING_LAVA", "LANDING_OBSIDIAN_TEAR", "LAVA", "MOB_APPEARANCE", "NAUTILUS", "NOTE", "PORTAL", "REDSTONE", "REVERSE_PORTAL", "SCRAPE", "SLIME", "SMALL_FLAME", "SMOKE_LARGE", "SMOKE_NORMAL", "SNEEZE", "SNOW_SHOVEL", "SNOWBALL", "SNOWFLAKE", "SOUL", "SOUL_FIRE_FLAME", "SPELL", "SPELL_INSTANT", "SPELL_MOB", "SPELL_MOB_AMBIENT", "SPELL_WITCH", "SPIT", "SPORE_BLOSSOM_AIR", "SQUID_INK", "SUSPENDED", "SUSPENDED_DEPTH", "SWEEP_ATTACK", "TOTEM", "TOWN_AURA", "VIBRATION", "VILLAGER_ANGRY", "VILLAGER_HAPPY", "WARPED_SPORE", "WATER_BUBBLE", "WATER_DROP", "WATER_SPLASH", "WATER_WAKE", "WAX_OFF", "WAX_ON", "WHITE_ASH"]

const particleAPINames = ["ASH", "BLOCK_CRACK", "BLOCK_DUST", "BLOCK_MARKER", "BUBBLE_COLUMN_UP", "BUBBLE_POP", "CAMPFIRE_COSY_SMOKE", "CAMPFIRE_SIGNAL_SMOKE", "CLOUD", "COMPOSTER", "CRIMSON_SPORE", "CRIT", "CRIT_MAGIC", "CURRENT_DOWN", "DAMAGE_INDICATOR", "DOLPHIN", "DRAGON_BREATH", "DRIP_LAVA", "DRIP_WATER", "DRIPPING_DRIPSTONE_LAVA", "DRIPPING_DRIPSTONE_WATER", "DRIPPING_HONEY", "DRIPPING_OBSIDIAN_TEAR", "DUST_COLOR_TRANSITION", "ELECTRIC_SPARK", "ENCHANTMENT_TABLE", "END_ROD", "EXPLOSION_HUGE", "EXPLOSION_LARGE", "EXPLOSION_NORMAL", "FALLING_DRIPSTONE_LAVA", "FALLING_DRIPSTONE_WATER", "FALLING_DUST", "FALLING_HONEY", "FALLING_LAVA", "FALLING_NECTAR", "FALLING_OBSIDIAN_TEAR", "FALLING_SPORE_BLOSSOM", "FALLING_WATER", "FIREWORKS_SPARK", "FLAME", "FLASH", "GLOW", "GLOW_SQUID_INK", "HEART", "ITEM_CRACK", "LANDING_HONEY", "LANDING_LAVA", "LANDING_OBSIDIAN_TEAR", "LAVA", "MOB_APPEARANCE", "NAUTILUS", "NOTE", "PORTAL", "REDSTONE", "REVERSE_PORTAL", "SCRAPE", "SLIME", "SMALL_FLAME", "SMOKE_LARGE", "SMOKE_NORMAL", "SNEEZE", "SNOW_SHOVEL", "SNOWBALL", "SNOWFLAKE", "SOUL", "SOUL_FIRE_FLAME", "SPELL", "SPELL_INSTANT", "SPELL_MOB", "SPELL_MOB_AMBIENT", "SPELL_WITCH", "SPIT", "SPORE_BLOSSOM_AIR", "SQUID_INK", "SUSPENDED", "SUSPENDED_DEPTH", "SWEEP_ATTACK", "TOTEM", "TOWN_AURA", "VIBRATION", "VILLAGER_ANGRY", "VILLAGER_HAPPY", "WARPED_SPORE", "WATER_BUBBLE", "WATER_DROP", "WATER_SPLASH", "WATER_WAKE", "WAX_OFF", "WAX_ON", "WHITE_ASH"]

const professionAPINames = ["ARMORER", "BUTCHER", "CARTOGRAPHER", "CLERIC", "FARMER", "FISHERMAN", "FLETCHER", "LEATHERWORKER", "LIBRARIAN", "MASON", "NITWIT", "NONE", "SHEPHERD", "TOOLSMITH", "WEAPONSMITH"]

const interactionTypeAPINames = ["NONE", "GUILD_GREETER", "CHAT", "CUSTOM_SHOP", "PROCEDURALLY_GENERATED_SHOP", "BAR", "ARENA", "QUEST_GIVER", "SELL", "TELEPORT_BACK", "SCRAPPER", "SMELTER", "REPAIRMAN", "ENHANCER", "REFINER", "UNBINDER", "ARENA_MASTER"]

const biomeAPINames = ["BADLANDS", "BAMBOO_JUNGLE", "BASALT_DELTAS", "BEACH", "BIRCH_FOREST", "COLD_OCEAN", "CRIMSON_FOREST", "CUSTOM", "DARK_FOREST", "DEEP_COLD_OCEAN", "DEEP_FROZEN_OCEAN", "DEEP_LUKEWARM_OCEAN", "DEEP_OCEAN", "DESERT", "DRIPSTONE_CAVES", "END_BARRENS", "END_HIGHLANDS", "END_MIDLANDS", "ERODED_BADLANDS", "FLOWER_FOREST", "FOREST", "FROZEN_OCEAN", "FROZEN_PEAKS", "FROZEN_RIVER", "GROVE", "ICE_SPIKES", "JAGGED_PEAKS", "JUNGLE", "LUKEWARM_OCEAN", "LUSH_CAVES", "MEADOW", "MUSHROOM_FIELDS", "NETHER_WASTES", "OCEAN", "OLD_GROWTH_BIRCH_FOREST", "OLD_GROWTH_PINE_TAIGA", "OLD_GROWTH_SPRUCE_TAIGA", "PLAINS", "RIVER", "SAVANNA", "SAVANNA_PLATEAU", "SMALL_END_ISLANDS", "SNOWY_BEACH", "SNOWY_PLAINS", "SNOWY_SLOPES", "SNOWY_TAIGA", "SOUL_SAND_VALLEY", "SPARSE_JUNGLE", "STONY_PEAKS", "STONY_SHORE", "SUNFLOWER_PLAINS", "SWAMP", "TAIGA", "THE_END", "THE_VOID", "WARM_OCEAN", "WARPED_FOREST", "WINDSWEPT_FOREST", "WINDSWEPT_GRAVELLY_HILLS", "WINDSWEPT_HILLS", "WINDSWEPT_SAVANNA", "WOODED_BADLANDS"]

const environmentAPINames = ["CUSTOM", "NETHER", "NORMAL", "THE_END"]

const moonPhaseAPINames = ["", "FULL_MOON", "WANING_GIBBOUS", "WANING_CRESCENT", "NEW_MOON", "WAXING_CRESCENT", "FIRST_QUARTER", "WAXING_GIBBOUS"]

//Util
function dragEnterHandler(event) {
    document.body.style.borderStyle = "dotted"
    document.body.style.borderColor = "green"
    document.body.style.borderRadius = "20px"
    document.body.style.borderWidth = "10px"
    event.preventDefault();
}

function dragLeaveHandler(event) {
    document.body.style.borderStyle = "none"
    event.preventDefault();
}

function dropHandler(event) {
    console.log('File(s) dropped');
    // Prevent default behavior (Prevent file from being opened)
    event.preventDefault();
    document.body.style.borderStyle = "none"

    if (event.dataTransfer.items) {
        // Use DataTransferItemList interface to access the file(s)
        [...event.dataTransfer.items].forEach((item, i) => {
            // If dropped items aren't files, reject them
            if (item.kind === 'file') {
                const file = item.getAsFile();
                console.log(`… file[${i}].name = ${file.name}`);
                console.log("running")

                file.text().then(function (getData) {
                    console.log(getData)
                    addModalDialogEntry(file.name, getData)
                })
            }
        });
    } else {
        // Use DataTransfer interface to access the file(s)
        [...event.dataTransfer.files].forEach((file, i) => {
            console.log(`… file[${i}].name = ${file.name}`);
        });
    }

    alert("Uploading files is not supported yet!")
}

function addModalDialogEntry(filename, text) {
    let modalEntryContainer = document.getElementById("modal-entry-container")
    console.log("1")

    if (modalEntryContainer == undefined) {
        console.log("2")
        let mainBox = document.createElement("div")
        mainBox.id = "modal-dialog-box"
        mainBox.style.overflow = "scroll"
        document.body.append(mainBox)

        let explanationText = document.createElement("p")
        mainBox.append(explanationText)
        explanationText.innerText = "You are now importing files!"

        modalEntryContainer = document.createElement("div")
        modalEntryContainer.id = "modal-entry-container"
        mainBox.append(modalEntryContainer)

        generateIndividualModalEntry(filename, modalEntryContainer)

        let doneButton = document.createElement("button")
        mainBox.append(doneButton)
        doneButton.classList.add("btn", "btn-primary")
        doneButton.innerText = "Submit"


        let bottomText = document.createElement("p")
        bottomText.id = "modal-box-footer"
        mainBox.append(bottomText)
        bottomText.innerText = "Note: your data does not get uploaded during this process.\n All data for the webapp is processed locally on your computer.\n"
        let githubLink = document.createElement("a")
        githubLink.href = "https://github.com/MagmaGuy/magmaguy.com/tree/master/webapp"
        githubLink.innerText = "Source code is available on github."
        githubLink.target = "_target"
        bottomText.append(githubLink)
    } else {
        generateIndividualModalEntry(filename, modalEntryContainer)
    }
}

function generateIndividualModalEntry(filename, modalEntryContainer) {
    let entry = document.createElement("div")
    modalEntryContainer.append(entry)
    entry.classList.add("row")

    let label = document.createElement("div")
    entry.append(filename)
    label.innerText = filename
    label.classList.add("col-sm-3")

    let select = document.createElement("select")
    entry.append(select)

    select.append(generateModalOption("custom_item"))
    select.append(generateModalOption("custom_boss"))
    select.append(generateModalOption("treasure_chest"))
    select.append(generateModalOption("npc"))
    select.append(generateModalOption("dungeon"))
    select.append(generateModalOption("arena"))
    select.append(generateModalOption("custom_event"))
    select.append(generateModalOption("custom_spawn"))
    select.append(generateModalOption("custom_quest"))
    select.append(generateModalOption("custom_power"))
    select.append(generateModalOption("wormhole"))
}

function generateModalOption(optionString) {
    let option = document.createElement("option")
    option.innerText = optionString
    option.value = optionString
    return option
}

/**
 * Searches for a parent by class name and then gets the first child by class name
 * @param currentElement Current element whose parent we will look for
 * @param parentClassName Class name of the parent, use the '.class' format
 * @param targetClassName Class name of the first child, use the '.class' format
 * @returns {*} First child of the parent with the specified class
 */
function diagonalDOMTraversal(currentElement, parentClassName, targetClassName) {
    return currentElement.closest(parentClassName).querySelector(targetClassName);
}

function expandEntry(expandButton) {
    const collapsibleContents = diagonalDOMTraversal(expandButton, '.container', '.main-container');
    if (collapsibleContents.classList.contains('collapse'))
        collapsibleContents.classList.remove('collapse');
    else
        collapsibleContents.classList.add("collapse");
}

/**
 * Moves card down
 * @param downButton Button that does the moving
 */
function arrowDown(downButton) {
//todo: remake
}

/**
 * Moves card up
 * @param upButton Button that does the moving
 */
function arrowUp(upButton) {
//todo: remake
}

/**
 * Slowly fades out any element and then removes it
 * @param element Element to fadeAnimation and delete
 */
function removeAnimation(element) {
    let op = 1;  // initial opacity
    const timer = setInterval(function () {
        if (op <= 0.1) {
            clearInterval(timer);
            element.style.display = 'none';
            element.remove();
        }
        element.style.opacity = op;
        element.style.filter = 'alpha(opacity=' + op * 100 + ")";
        op -= op * 0.5;
    }, 50);
}

//resize
window.addEventListener('resize', resizeCardContainer)

function resizeCardContainer() {
    const width = window.innerWidth
    let containers = document.getElementsByClassName("container")
    if (width < 2000) {
        for (let i = 0; i < containers.length; i++)
            containers[i].classList.add("container-slim")
    } else {
        for (let i = 0; i < containers.length; i++)
            containers[i].classList.remove("container-slim")
    }
}


//new stuff ----------------------------------------------------------------------------------------------------------------------------
//new field generation
function generateGenericCard(button) {
    //Whole-ass card todo: this doesn't actually create a fully generic card right now
    let cardContainer = document.createElement("div")
    cardContainer.classList.add("container", "col-8")

    //Contents first for the collapsible part but add them as a child node later
    let cardContents = document.createElement("div")
    cardContents.classList.add("card", "card-contents")

    generateContentSelector(cardContents)

    //Top toolbar
    let toolbar = document.createElement("div")
    toolbar.classList.add("row", "toolbar")
    cardContainer.appendChild(toolbar)

    let toolbarTitle = document.createElement("div")
    toolbarTitle.classList.add("card-title")
    toolbar.appendChild(toolbarTitle)

    let toolbarIcons = document.createElement("div")
    toolbarIcons.classList.add("toolbar-icons")
    toolbar.appendChild(toolbarIcons)

    let toolbarMinimize = createInvisibleButton(function () {
        if (cardContents.classList.contains("collapse"))
            cardContents.classList.remove("collapse")
        else
            cardContents.classList.add("collapse")
    })
    toolbarMinimize.appendChild(getExpandIcon())
    toolbarIcons.appendChild(toolbarMinimize)

    let toolbarMoveUp = createInvisibleButton()
    toolbarMoveUp.appendChild(getArrowUpIcon())
    toolbarIcons.appendChild(toolbarMoveUp)

    let toolbarMoveDown = createInvisibleButton()
    toolbarMoveDown.appendChild(getArrowDownIcon())
    toolbarIcons.appendChild(toolbarMoveDown)

    let toolbarDelete = createInvisibleButton(function () {
        simplifiedCardDelete(this)
    })
    toolbarDelete.appendChild(getTrashIcon())
    toolbarIcons.appendChild(toolbarDelete)

    //Add contents now to the main card
    cardContainer.appendChild(cardContents)

    document.body.append(cardContainer)
    document.body.append(button.parentNode)
    document.body.append(document.getElementById("generate").parentNode)

    resizeCardContainer()
}

function generateTemplatesCard(cardContents, text, link) {
    cardContents.innerHTML = ""
    let cardHeader = document.createElement("h3")
    cardHeader.innerHTML = "Create "
    let anchor = document.createElement("a")
    anchor.innerText = text
    anchor.href = link
    anchor.target = "_blank"
    cardHeader.appendChild(anchor)
    cardHeader.innerHTML += "!"
    cardHeader.classList.add("text-center")
    cardContents.append(cardHeader)

    let innerCard = document.createElement("div")
    innerCard.classList.add("inner-card")
    cardContents.append(innerCard)

    let pickATemplate = document.createElement("h4")
    pickATemplate.innerText = "Pick a template!"

    let templateContainer = document.createElement("div")
    templateContainer.append(pickATemplate)
    templateContainer.classList.add("text-center", "template-container")
    innerCard.append(templateContainer)

    cardContents.append(innerCard)

    return templateContainer
}

function generateTemplateOption(name, templateCreationFunction, templateContainer) {
    let templateButton = document.createElement("button")
    templateButton.onclick = templateCreationFunction
    templateButton.innerText = name
    templateButton.classList.add("btn-primary", "col-sm-4", "template-button")
    templateContainer.appendChild(templateButton)
}

function generateContentSelector(cardContents) {
    let header = document.createElement("h4")
    header.innerText = "Pick your creation!"
    cardContents.append(header)
    generateContentButton("Custom Item", function () {
        createCustomItemsTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Custom Boss", function () {
        createCustomBossesTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Treasure Chest", function () {
        createTreasureChestTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("NPC", function () {
        createNPCTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Dungeon", function () {
        createDungeonTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Arena", function (){
        createArenaTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Custom Event", function () {
        createCustomEventsTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Custom Spawn", function () {
        createCustomSpawnsTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Custom Quest", function () {
        createCustomQuestTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Wormhole", function () {
        createWormholeTemplateCard(cardContents)
    }, cardContents, true)
    generateContentButton("Custom Power", function () {
        createEliteScriptsTemplateCard(cardContents)
    }, cardContents, true)
}

function generateContentButton(text, clickFunction, cardContents, enabled) {
    let contentButton = document.createElement("button")
    contentButton.innerText = text
    contentButton.onclick = clickFunction
    contentButton.classList.add("col-sm-4", "template-button", "btn-primary")
    if (!enabled)
        contentButton.classList.add("disabled")
    cardContents.append(contentButton)
}

function simplifiedCardTitleUpdate(cardContents, newTitle) {
    cardContents.closest(".container").getElementsByClassName("card-title")[0].innerText = newTitle;
}

function simplifiedCardDelete(button) {
    removeAnimation(button.closest(".container"))
}

function createInvisibleButton(buttonOnClick) {
    let invisibleButton = document.createElement("button")
    invisibleButton.classList.add("invisible-button")
    invisibleButton.onclick = buttonOnClick
    return invisibleButton
}

function createFilenameField(innerCard) {
    let textField = createTextField(innerCard, "filename", "Filename", "").getElementsByTagName("input")[0]
    tagRequired(textField)
    textField.onkeyup = function () {
        simplifiedCardTitleUpdate(innerCard, textField.value)
    }
}

function createGenericEntry(container, keyText, keyLink) {
    let entryDiv = document.createElement("div")
    setGenericConfigEntry(entryDiv)
    entryDiv.classList.add("row")
    entryDiv.append(createKey(keyText, keyLink))
    return entryDiv
}

function createTextField(container, configKey, keyText, keyLink, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)

    let textField = document.createElement("input")
    textField.type = "text"
    textField.dataset.configKey = configKey
    textField.dataset.inputType = "text"
    textField.setAttribute("data-toggle", "tooltip")
    textField.setAttribute("data-placement", "right")
    textField.placeholder = "string"

    textField.classList.add("form-control", "col-sm-8")
    if (required === true) tagRequired(textField)

    entryDiv.append(textField)
    container.append(entryDiv)
    return entryDiv
}

function createTextFields(container, configKey, keyText, keyLink, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)
    setAsConfigList(entryDiv, configKey)
    setGenericConfigEntry(entryDiv)

    let inputList = document.createElement("div")
    inputList.classList.add("multiple-input-container", "col-sm-8")
    entryDiv.append(inputList)

    let inputPair = document.createElement("div")
    inputPair.classList.add("multiple-input-pair", "row", "col-sm-12")
    inputList.append(inputPair)
    setGenericConfigEntry(inputPair)

    let inputElement = document.createElement("input")
    inputElement.classList.add("form-control", "col-sm-11")
    inputElement.dataset.inputType = "text"

    if (required === true) tagRequired(inputElement)

    inputPair.append(inputElement)

    let trashIcon = createInvisibleButton(function () {
        removeAnimation(this.closest(".multiple-input-pair"))
    })
    trashIcon.append(getTrashIcon())
    trashIcon.classList.add("col-sm-1")

    inputPair.append(trashIcon)

    container.append(entryDiv)

    let newButton = createInvisibleButton(function () {
        let clonedDom = inputPair.cloneNode(true)
        inputList.append(clonedDom)
        inputList.append(this)
        clonedDom.getElementsByTagName("button")[0].onclick = function () {
            removeAnimation(this.closest(".multiple-input-pair"))
        }
        clonedDom.getElementsByTagName("input")[0].value = ""
    })
    newButton.classList.add("invisible-button", "row")
    newButton.append(getPlusIcon())
    inputList.append(newButton)

    return inputElement
}

function createIntegerField(container, configKey, keyText, keyLink, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)

    let integerField = document.createElement("input")
    integerField.dataset.configKey = configKey

    integerField.type = "text"
    integerField.setAttribute("data-toggle", "tooltip")
    integerField.setAttribute("data-placement", "right")
    integerField.dataset.inputType = "integer"
    integerField.placeholder = "number"

    integerField.classList.add("form-control", "col-sm-8")
    if (required === true) tagRequired(integerField)

    entryDiv.append(integerField)
    container.append(entryDiv)
    return entryDiv
}

function createBooleanField(container, configKey, keyText, keyLink, required) {
    createListField(container, configKey, keyText, keyLink, ["", "true", "false"], required)
}

function createListField(container, configKey, keyText, keyLink, options, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)

    let selection = document.createElement("select")
    selection.classList.add("form-control", "col-sm-8")
    selection.dataset.configKey = configKey

    if (required === true) tagRequired(selection)

    for (let i = 0; i < options.length; i++) {
        let optionElement = document.createElement("option")
        optionElement.innerText = options[i]
        optionElement.value = options[i]
        selection.append(optionElement)
    }

    entryDiv.append(selection)

    container.append(entryDiv)
    return selection
}

function createMultiSelectListField(container, configKey, keyText, keyLink, options, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)
    setAsConfigList(entryDiv, configKey)

    let allSelectionsContainer = document.createElement("div")
    entryDiv.append(allSelectionsContainer)

    createSingleSelectForMultiSelectField(allSelectionsContainer, options, required)

    let addButton = createInvisibleButton(function () {
        createSingleSelectForMultiSelectField(allSelectionsContainer, options, required)
    })
    addButton.append(getPlusIcon())
    allSelectionsContainer.append(addButton)
}

function createSingleSelectForMultiSelectField(allSelectionsContainer, options, required) {
    let singleSelectionContainer = document.createElement("div")
    singleSelectionContainer.classList.add("row")
    allSelectionsContainer.append(singleSelectionContainer)
    setGenericConfigEntry(singleSelectionContainer)

    let selection = document.createElement("select")
    selection.classList.add("form-control", "col-sm-7")
    singleSelectionContainer.append(selection)

    let deleteButton = createInvisibleButton(function () {
        removeAnimation(singleSelectionContainer)
    })
    deleteButton.classList.add("col-sm-1")
    deleteButton.append(getTrashIcon())
    singleSelectionContainer.append(deleteButton)

    if (required === true) tagRequired(selection)

    for (let i = 0; i < options.length; i++) {
        let optionElement = document.createElement("option")
        optionElement.innerText = options[i]
        optionElement.value = options[i]
        selection.append(optionElement)
    }
}

function createVectorField(container, configKey, keyText, keyLink, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)
    setAsSplitByCommas(entryDiv)
    entryDiv.dataset.configKey = configKey

    let xLabel = generateComplexLabel("x:")
    let yLabel = generateComplexLabel("y:")
    let zLabel = generateComplexLabel("z:")
    let xField = generateComplexInput("1", "col-sm-2")
    let yField = generateComplexInput("1", "col-sm-2")
    let zField = generateComplexInput("1", "col-sm-2")

    if (required === true) {
        tagRequired(xField)
        tagRequired(yField)
        tagRequired(zField)
    }

    entryDiv.append(xLabel, xField, yLabel, yField, zLabel, zField)
    container.append(entryDiv)
    return entryDiv
}

function generateComplexLabel(text) {
    let complexLabel = document.createElement("div")
    complexLabel.innerText = text
    complexLabel.style.marginLeft = "5px"
    complexLabel.style.marginRight = "5px"
    return complexLabel
}

function generateComplexInput(placeholder, width, options) {
    if (options === undefined) {
        let complexField = document.createElement("input")
        complexField.type = "text"
        complexField.placeholder = placeholder
        complexField.classList.add("form-control", width)
        return complexField
    } else {
        let complexField = document.createElement("select")
        complexField.placeholder = placeholder
        complexField.classList.add("form-control", width)
        for (let i = 0; i < options.length; i++) {
            let optionElement = document.createElement("option")
            optionElement.innerText = options[i]
            optionElement.value = options[i]
            complexField.append(optionElement)
        }
        return complexField
    }
}

function createLocationField(container, configKey, keyText, keyLink, required) {
    let entryDiv = createGenericEntry(container, keyText, keyLink)
    setAsSplitByCommas(entryDiv)
    entryDiv.dataset.configKey = configKey
    entryDiv.classList.add("config-location-string")

    let worldLabel = generateComplexLabel("World name:")
    let xLabel = generateComplexLabel("x:")
    let yLabel = generateComplexLabel("y:")
    let zLabel = generateComplexLabel("z:")
    let pitchLabel = generateComplexLabel("Pitch:")
    let yawLabel = generateComplexLabel("Yaw:")
    let worldField = generateComplexInput("myWorld", "col-sm-3")
    let xField = generateComplexInput("1", "col-sm-0")
    let yField = generateComplexInput("1", "col-sm-0")
    let zField = generateComplexInput("1", "col-sm-0")
    let pitchField = generateComplexInput("0", "col-sm-0")
    let yawField = generateComplexInput("0", "col-sm-0")

    if (required === true) {
        tagRequired(worldField)
        tagRequired(xField)
        tagRequired(yField)
        tagRequired(zField)
    }

    entryDiv.append(worldLabel, worldField, xLabel, xField, yLabel, yField, zLabel, zField, pitchLabel, pitchField, yawLabel, yawField)
    container.append(entryDiv)
    return entryDiv
}

function createKey(keyText, keyLink) {
    let keyDiv = document.createElement("div")
    keyDiv.innerText = keyText;
    keyDiv.classList.add("col-sm-3")
    if (keyLink != null && keyLink !== "") {
        let anchor = document.createElement("a")
        anchor.href = keyLink
        anchor.target = "_blank"
        anchor.append(getZoomIcon())
        keyDiv.append(anchor)
    }
    return keyDiv
}

function createGlobalTemplate(templateContainer) {
    let innerCard = templateContainer.closest(".inner-card")
    templateContainer.remove()
    createFilenameField(innerCard)
    return innerCard
}

//icons

function getPlusIcon() {
    return document.getElementById("template-plus-icon").content.cloneNode(true)
}

function getTrashIcon() {
    return document.getElementById("template-trash-icon").content.cloneNode(true)
}

function getScriptTrashIcon() {
    return document.getElementById("template-script-trash-icon").content.cloneNode(true)
}

function getArrowUpIcon() {
    return document.getElementById("template-up-arrow-icon").content.cloneNode(true)
}

function getArrowDownIcon() {
    return document.getElementById("template-down-arrow-icon").content.cloneNode(true)
}

function getExpandIcon() {
    return document.getElementById("template-expand-icon").content.cloneNode(true)
}

function getZoomIcon() {
    return document.getElementById("template-zoom-icon").content.cloneNode(true)
}

function getDuplicateIcon() {
    return document.getElementById("template-duplicate-icon").content.cloneNode(true)
}